### PR TITLE
sdlog2 fixes

### LINKED ISSUE #4108: Snapdragon/SITL: mainapp can crash on disarm
Sometimes, maybe 1/5 times. I disarm and get:

```
*** Error in `./mainapp': double free or corruption (fasttop): 0xb4800468 ***
Aborted
```

### PR DESCRIPTION
**Pull request by julianoes**
This fixes #4108, as well as a second bug where `sdlog2 start` without more arguments would cause a segfault.

### CODE REVIEW

**Comment by sanderux** [comment]
Does this also fix https://github.com/PX4/Firmware/issues/4080 ?

**Comment by julianoes** [comment]
@sanderux I don't think it does. It only fixes the crash on disarm (when free happens).

File: src/modules/sdlog2/sdlog2.c [hunk 1]
```diff
@@ -936,9 +936,12 @@ int sdlog2_thread_main(int argc, char *argv[])
 
 	flag_system_armed = false;
 
-	/* work around some stupidity in task_create's argv handling */
+#ifdef __PX4_NUTTX
```
Comment (LorenzMeier) [inline src/modules/sdlog2/sdlog2.c]: @julianoes Please don't remove workarounds without in-depth discussion and on-hardware cross checks.

Comment (julianoes) [inline src/modules/sdlog2/sdlog2.c]: I tested it on NuttX though
