### PR TITLE
Fix usage of errno in POSIX semaphore error handling

### LINKED ISSUE #11118: Commander spams the nsh console on SITL
**Describe the bug**
On the process of testing the micro RTPS bridge between a SITL client (with Gazebo) and the agent, I get the following warning msgs on the output of the `nsh` console:
```sh
WARN  [px4] commander: px4_sem_timedwait failure: ret: 110, Connection timed out
WARN  [cdev] commander: px4_poll() sem error: Success
WARN  [px4] commander: px4_sem_timedwait failure: ret: 110, Connection timed out
WARN  [cdev] commander: px4_poll() sem error: Success
```
which repeat themselves over time. The same does not happen if one builds the posix build using `_default` instead of `_rtps`.

I am testing latest upstream master. This may have been introduced by the latest changes on SITL and with the lockstep feature.

I am currently trying to find if this is just a warning or if this is introducing some sort of problem or breaking some functionality. Though, this wasn't happening before.

@julianoes @MaEtUgR any tips on what's causing this?

**To Reproduce**
Platform: Ubuntu 18.04 with Gazebo 9.

1. Clone upstream master;
2. Issue `make px4_sitl_rtps gazebo`;
3. Observe the above lines on the `nsh` console output.

**Expected behavior**
A clean console output.

**Log Files and Screenshots**
screenshot from 2018-12-31 13-15-03

### PR DESCRIPTION
**Pull request by LorenzMeier**
Previous commit 98ae0186e93 changed the err variable to errno, which is not the return value we are looking for.

Fixes #11118.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This is the proper fix. Please read the whole file to see how `errno` is being used to initialize it correctly for outer consumers. It is never used as an internal status.

**Comment by julianoes** [comment]
Ok, I see what's going on. I misread the `pthread_cond_timedwait` spec. It actually does return the errno or 0.
http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_timedwait.html

This means the lockstep implementation is wrong and needs to be changed as well.

**Comment by julianoes** [comment]
Please hold off with merging this because I think it might cause output or errors for the lockstep implementation. I'll fix the lockstep API and then include this fix.

**Comment by LorenzMeier** [comment]
Please also note that errno is a *GLOBAL* variable and a leftover from the very, very early days of single-thread operating systems. You should never use the variable directly in a modern implementation because of that.

> In addition, all POSIX.1c functions avoid using errno and, instead, return the error number directly as the function return value, with a return value of zero indicating that no error was detected. This strategy is, in fact, being followed on a POSIX-wide basis for all new functions.

http://pubs.opengroup.org/onlinepubs/009695399/functions/errno.html

http://www.unix.org/whitepapers/reentrant.html

**Comment by julianoes** [comment]
Right, makes perfect sense.

So this will need to change :smile::
https://github.com/PX4/Firmware/blob/065f97e87ba76664b8db8b7a35507e3ecf2afec7/platforms/posix/src/lockstep_scheduler/src/lockstep_scheduler.cpp#L82-L85

**Comment by julianoes** [comment]
Ah, now I get it. The confusion came from the API of `sem_timedwait` which uses `errno`.
http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_timedwait.html

**Comment by julianoes** [comment]
@LorenzMeier I've added commits to change the API of the lockstep scheduler, and also to set `errno` of `sem_timedwait`. I think this is correct now. I'd appreciate a review.

File: platforms/posix/src/px4_layer/px4_sem.cpp [hunk 1]
```diff
@@ -140,20 +140,24 @@ int px4_sem_timedwait(px4_sem_t *s, const struct timespec *abstime)
...
 		char thread_name[NAMELEN] = {};
 		(void)pthread_getname_np(pthread_self(), thread_name, NAMELEN);
-		PX4_WARN("%s: px4_sem_timedwait failure: ret: %d, %s", thread_name, ret, strerror(err));
+		PX4_WARN("%s: px4_sem_timedwait failure: ret: %d, %s", thread_name, ret, strerror(ret));
 	}
 
 	int mret = pthread_mutex_unlock(&(s->lock));
 
-	return (err) ? err : mret;
+	if (ret || mret) {
```
Comment (LorenzMeier) [inline platforms/posix/src/px4_layer/px4_sem.cpp]: Correct. http://pubs.opengroup.org/onlinepubs/9699919799/functions/sem_timedwait.html
