### PR TITLE
Fix RC mode switch first evaluation after boot

### LINKED ISSUE #11914: RC mode switch not always applied on first RC link connection after boot
When PX4 boots it's main state is initialized to "Manual" and one of the most common use cases is that the user connects his RC and starts to fly. But the mode doesn't always get taken from the RC switch on bootup.

I already did some investigation on this issue and found that the problem is in the currently unreadable condition when to reconsider the mode switch. I already have a working branch where I cleaned it up and am finalizing the solution following up with the pr very soon.

### PR DESCRIPTION
**Pull request by MaEtUgR**
**Describe problem solved by the proposed pull request**
Fixes #11914
First two commits are refactoring to make the analyzed condition readable. The last commit fixes the problem that sometimes the mode chosen by the RC switch does not get evaluated after bootup when the RC connects for the first time. Result was it stayed in "Manual" mode which can lead to unexpected behavior e.g. switch is in altitude or position mode state but does not get applied when not flicking the mode switch back and forth once.

**Test data / coverage**
I tested this the same way I debugged the problem: In SITL and with the virtual controller overlay feature in QGC. Using the virtual controller results in having the initialization values which are zeros in the manual control setpoint for the "unused" fields e.g. mode_slot. And a zero in mode_slot is the first configured mode. So I configured the first mode to "Acro" and did my testing. I tried turning on with RC, turning on without RC and ticking the virtual joystick shortly after to get RC and waiting until position is locked and then connecting the RC. The last case also worked by accident before because if you gain position lock you reconsider the RC mode switch and the whole condition (`_last_condition_global_position_valid`) is only updated when there's RC at all. 

**Additional context**
I found additional unwanted corner cases e.g. with the position lock gained condition while debugging this but I don't consider them release blocking and I'll open issues for them separately.

FYI @DanielePettenuzzo

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@PX4/testflights Please test on multicopter

File: src/modules/commander/Commander.cpp [hunk 1]
```diff
@@ -2731,22 +2731,25 @@ Commander::set_main_state_rc(const vehicle_status_s &status_local, bool *changed
...
-		&& (_last_sp_man.rattitude_switch == sp_man.rattitude_switch)
-		&& (_last_sp_man.posctl_switch == sp_man.posctl_switch)
-		&& (_last_sp_man.loiter_switch == sp_man.loiter_switch)
-		&& (_last_sp_man.mode_slot == sp_man.mode_slot)
-		&& (_last_sp_man.stab_switch == sp_man.stab_switch)
-		&& (_last_sp_man.man_switch == sp_man.man_switch);
-
-	/* manual setpoint has not updated, do not re-evaluate it */
-	if (!position_got_valid && ((had_rc_before && rc_values_not_updated) || all_switches_stayed)) {
+	const bool first_time_rc = _last_sp_man.timestamp == 0;
```
Comment (bkueng) [inline src/modules/commander/Commander.cpp]: This works because the `set_main_state_rc` call is conditioned by `sp_man.timestamp != 0`.
For consistency I'd consider adding that check here as well.

**Comment by LorenzMeier** [comment]
@Tony3dr Why didn't we get flights in yesterday?

File: src/modules/commander/Commander.cpp (hunk 1 above)
Comment (MaEtUgR) [reply src/modules/commander/Commander.cpp]: Thanks for checking!
You're right. There's even a duplicate such condition here: https://github.com/PX4/Firmware/blob/903deb7579ec655ffea526eb5701b78f9f5c9ce8/src/modules/commander/Commander.cpp#L2084 I'll quickly add this.

Sadly there are more potential corner cases that start with "It works because it's conditioned..." E.g. `_last_condition_global_position_valid` only gets updated when you have RC and `_last_sp_man` only gets updated when you evaluate the mode switch or are in a manual mode. I want to refactor to get rid of these obfuscated cases but not before the release. I hope it's ok to leave it for this pr.

**Comment by MaEtUgR** [comment]
Testing on the real vehicle I found:
- This change seems fine and fixes the problem where the switch is in slot 1 (value 0) doesn't get evaluated on boot.
- There's still a remaining problem when you have the switch set to altitude because the altitude estimate is not initialized and it automatically falls back to Stabilized without reevaluating when the altitude is available.

I'll need to follow up with a fix of the second point.

File: src/modules/commander/Commander.cpp (hunk 1 above)
Comment (julianoes) [reply src/modules/commander/Commander.cpp]: I always like brackets around conditions, I think it's more readable:

```suggestion
	const bool first_time_rc = (_last_sp_man.timestamp == 0);
```

File: src/modules/commander/Commander.cpp [hunk 2]
```diff
@@ -2730,20 +2730,27 @@ Commander::set_main_state_rc(const vehicle_status_s &status_local, bool *changed
...
+		|| (_last_sp_man.mode_slot != sp_man.mode_slot)
+		|| (_last_sp_man.stab_switch != sp_man.stab_switch)
+		|| (_last_sp_man.man_switch != sp_man.man_switch);
+
+	// only switch mode based on RC switch if necessary to also allow mode switching via MAVLink
+	const bool should_evaluate_rc_mode_switch = first_time_rc
+			|| position_got_valid
+			|| (rc_values_updated && some_switch_changed);
+
+	if (!should_evaluate_rc_mode_switch) {
```
Comment (julianoes) [inline src/modules/commander/Commander.cpp]: So I'm trying to understand: we are setting this variabe on whether we should evaluate the RC mode switch. If we find that we should evaluate it, then we don't actually do anything. And if we should not evaluate it, then we do something? What am I missing?

Comment (LorenzMeier) [reply src/modules/commander/Commander.cpp]: Its code that is exiting the routine early, instead of running through the rest. If you unfold it, you will see.

Comment (julianoes) [reply src/modules/commander/Commander.cpp]: Ah right, that's tricky!

**Comment by Tony3dr** [comment]
> @Tony3dr Why didn't we get flights in yesterday?

@LorenzMeier we are in PST the Team heads out to the field early in the morning. The PR was assigned at 2 pm PST. Yesterday the Team flew Master, PR will be tested today.

File: src/modules/commander/Commander.cpp (hunk 2 above)
Comment (MaEtUgR) [reply src/modules/commander/Commander.cpp]: I wasn't comfortable to change the whole structure just before release. I'm happy to rip it apart afterwards. E.g.
```
if(should_evaluate_rc_mode_switch) {
    set_main_state_rc(...);
}
```

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk4 mini v5

**Modes Tested** 
- Position Mode: Good. 
- Altitude Mode: Good. 
- Stabilized Mode: Good. 
- Mission Plan Mode (Automated): Good. 

**Procedure**
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour. 

**Notes**
No issues noted, good flight in general. 
All modes were tested and switches were successful without delay.

**Logs:**
- https://review.px4.io/plot_app?log=e567a5f7-3ec3-4d0f-8fb0-dc35382213a8

After a complete reboot we followed the same procedure.
- https://review.px4.io/plot_app?log=d6b6de47-d10f-48c3-8a83-9ade2b2bc13b

**Comment by jorge789** [comment]
Tested on Pixhawk 2 Cube v3:

 - Modes Tested
Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
- Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoin activate RTL and see landing behaviour.

NOTE: No issues noted,good flight in general.
All modes were tested and switches were successful without delay.

Log
https://review.px4.io/plot_app?log=84a6e7d3-7daa-4354-8b4f-3e51f0f55281

After a complete reboot we followed the same procedure.

https://review.px4.io/plot_app?log=0425d680-8c7c-4ab7-ac2a-c78d41d92e23

Tested on PixRacer V4:

Modes Tested

Position Mode: Good.
Altitude Mode: Good.
Stabilized Mode: Good.
Mission Plan Mode (Automated): Good.
Procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

Notes
No issues noted, good flight in general.
All modes were tested and switches were successful without delay.

Logs:

https://review.px4.io/plot_app?log=039b2bd6-0b10-42b2-83dd-accdaf32331e

After a complete reboot we followed the same procedure.

https://review.px4.io/plot_app?log=23881a75-08c5-4a4f-8ea1-0e47ec9e1928

**Comment by dannyfpv** [comment]
tested on pixhawk 4 v5 
Modes Tested

Position Mode: No issues
altitude Mode: No issues
Stabilized Mode: No issues
mission Plan Mode: No issues
procedure
Arm and Take off in position mode, after flying for approximately one minute, switched to altitude then stabilized mode proceed to switch to mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint activate RTL and see landing behaviour.

Notes
Good flight in general.
All modes were tested and switches were successful without delay.ttps://review.px4.io/plot_app?log=9ca8bff9-ff42-47a6-b50d-e7f1902f6ef9
ttps://review.px4.io/plot_app?log=8af5fe02-dc8b-44ed-9d79-aac1f1750956

File: src/modules/commander/Commander.cpp (hunk 1 above)
Comment (MaEtUgR) [reply src/modules/commander/Commander.cpp]: I'm also a fan of brackets if there are more than one operator and two operands on the right side of the assignment.

**Comment by MaEtUgR** [comment]
> There's still a remaining problem when you have the switch set to altitude because the altitude estimate is not initialized and it automatically falls back to Stabilized without reevaluating when the altitude is available.
> I'll need to follow up with a fix.

#11928
