### PR TITLE
AttPosEKF Fix for inhibit mag state for fly-forward for multicopters

### LINKED ISSUE #1871: Check fly-forward setting of EKF for multicopters.
@priseborough What do we need to obey when using the mag offset estimation on multicopters in the test harness?

### PR DESCRIPTION
**Pull request by Zefz**
This fixes #1871 by inhibiting mag offset if we are multicopter that is hovering without any deliberate accelerations (0.5 m/s)

### CODE REVIEW

File: src/modules/ekf_att_pos_estimator/estimator_utilities.cpp [hunk 1]
```diff
@@ -38,6 +38,7 @@
  */
 
 #include "estimator_utilities.h"
+#include <algorithm>
```
Comment (LorenzMeier) [inline src/modules/ekf_att_pos_estimator/estimator_utilities.cpp]: I would like to avoid baking in C++11 bits. It compiles now on this platform, but some higher-end platforms actually only have C++03.

**Comment by LorenzMeier** [comment]
Many thanks! Looks good, except for the comment I made. Is this flight-tested?

**Comment by Zefz** [comment]
Only one flight, there was a different bug that caused some yaw problems but other than that it flied auto waypoints without any issues.

**Comment by LorenzMeier** [comment]
@kd0aij Would you be interested to test-fly this branch?

**Comment by Zefz** [comment]
I think I got some logic swapped around making the inhibitMagStates do actually opposite of what it was supposed to! Fixed it in cdbd687.

**Comment by Zefz** [comment]
Ah crap, seems I commited to early. Fixed!

**Comment by kd0aij** [comment]
test flight log: http://dash.oznet.ch/view/XeBQYRRLygJ8DKEFxhujmF
Manual mode (GPS is poor under the trees). Hovered attempting to keep ||V|| small, facing N,S,E and W. Observed no uncommanded yaw and controls felt good; 
@LorenzMeier: increased roll/pitch P gains from last flight). Noticed in logs a large discrepancy in roll vs rollSP and found the battery was off center :) Currently the roll/pitch I terms are zero. 
@Zefz: Let me know if there's a better test procedure you'd like me to try.

**Comment by Zefz** [comment]
Yaw estimation seems very accurate according to the logs, the difference between setpoint and measured yaw is very small. This is good because it means we have little noise in yaw estimation.
as_yaw

I see there is a constant offset between the roll rate setpoint and actual roll rate. Is this normal? Seems to me the attitude controller is requesting about 0.5 radians (30 degrees/second) rotation rate while actual output is about zero. Is this compensation for wind perhaps?
a_rollrate

**Comment by kd0aij** [comment]
I also noticed the large discrepancy in roll vs rollSP and found the battery was off center to the left :) Currently the roll/pitch I terms are zero. Without an I term, there will be a steady-state error signal proportional to the torque required to offset the out-of-balance condition. This explains the offset in rollSP calling for right-roll torque.
I agree that yaw performance looks OK. Are there any other logged parameters that we might look at to validate the change?

**Comment by kd0aij** [comment]
Another test flight with some Integrator gain added in for roll and pitch rate. Still no problems with yaw.
http://dash.oznet.ch/view/633LRCpsj4TaGiGNivSYqU
Went to ALTCTL for a short time; altitude didn't hold well, presumably because GPS altitude was all over the place. Actual altitude was between 1 and 3 meters AGL most of the time.

**Comment by LorenzMeier** [comment]
@kd0aij Thanks! If you look at the altitude tracking:
http://dash.oznet.ch/view/633LRCpsj4TaGiGNivSYqU#Local_Z_PLOT

It actually looks like it tracked altitude quite well! The input is mapped from stick center up and down. So you would need to put your stick to center after switching to althold and it should hold the altitude then.

**Comment by LorenzMeier** [comment]
And GPS is not used in althold at all, and GPS altitude in general only to offset baro drift.

**Comment by kd0aij** [comment]
:) The only reason I was moving the left stick is because the quad was moving up and down

**Comment by kd0aij** [comment]
Actually, that does correlate very well, if the change in thrust required for descent is barely noticeable.

**Comment by LorenzMeier** [comment]
Awesome, many thanks!

**Comment by LorenzMeier** [comment]
@kd0aij No, you didn't change trust. You moved the Z reference up and down. You just need to center your stick (its an usage / manual input problem, not a control problem). If you would spring-load your throttle it would become much easier, as you just would need to let go.

**Comment by kd0aij** [comment]
Another observation from that log: it seems my ER9x/FrSky RC control had a major glitch on pitch (RC channel 1). Also shows that I probably need to reduce the D gain on pitch/roll.
rcglitch
This is worrying; I don't recall hearing any beeps from the FrSky TX module indicating dropped packets and the last thing I need is unreliable manual control.
