### PR TITLE
RC Failsafe fix for RFD 868+/900 Modems

### LINKED ISSUE #12381: Critical RC Loss Failsafe Bug, Potenial Vehicle Lost
**Describe the bug**
Hello, I'm using PX4 latest Firmware in Pixhawk 2.1 (Cube). Geometry is generic Quadrotor X geometry. My communication system is depending on RF modules(Long range ~900MHz) between Vehicle and RC. I'm feeding Pixhawk RC_IN with RF PPM signal out which is on RC. Radio Controller's (FrSky Taranis X9D) PPM frame length is 22.5 ms and it has 8 channels. Failsafe action was RTL.

Yesterday, I was trying failsafe actions. While I was trying RC Loss failsafe, I just power off  RC by manual and failsafe action wasn't triggered. Then, Vehicle just fell down. 
I just examined log data. I explored PPM signal didn't cut off by RF.
Screenshot from 2019-07-01 15-28-29

PX4 thought PPM signal wasn't cut off. RF is sending continuously PPM signal which has 12 channels when RX-TX communication is lost. Channels have 1 ms frame length and PPM frame length is 24ms which has to be 22.5ms. 

The problem is that RF module sends PPM signal even RC signal is lost. It also send 1ms signal which is meaning lowest signal strength for channels. So, failsafe action isn't triggered by itself which causes vehicle fall.

**To Reproduce**
1. Drone switched on.
2. RC switched on.
3. Took off with any mode.
4. Cut off RC power.
5. See error.

**Expected behavior**
When RC signal lost, failsafe should be triggered independently of RF PPM signal. Also, number of channels and frame length shouldn't be change itself when vehicle is armed.

**Log Files and Screenshots**
When RC signal is normal.
IMG_20190701_131840

When RC signal is went off.
IMG_20190701_131758

RC frame and channel info.
IMG_20190701_131919

**Possible solutions:**
For my case, I just changed this line:
https://github.com/PX4/Firmware/blob/528d2f61a0ac30daa100f06de0cc78dcc072e43e/src/modules/sensors/rc_update.cpp#L230
To this:
` if (rc_input.rc_lost || rc_input.rc_failsafe || rc_input.channel_count > 8)`
It works but I know it is dirty solution. 

**Solution 1:**
We should change line which is constrain value of this message:
https://github.com/PX4/Firmware/blob/cc68775defa8432560bd7bb90a038d9e7c0fa8c9/msg/input_rc.msg#L22
And the number of channel should change by only calibrating RC. When number of channels is  changed on armed state, failsafe should be triggered.

**Solution 2:**
PPM frame length also has constraint value by RC. When PPM frame length changes unexpectedly, failsafe should be triggered.

### PR DESCRIPTION
**Pull request by julianoes**
RC Failsafe isn't triggered when PPM signal is valid. These changes
update Failsafe trigger logic for RC input. RF Modules keep sending
valid PPM signal when the RC Transmitter is lost.
RF Modules which are in the air send PPM signal with same type when lost
the signal from ground.

Replacement for #12595.

Fixes #12381.

### CODE REVIEW

File: src/modules/sensors/rc_update.cpp [hunk 1]
```diff
@@ -228,6 +228,23 @@ RCUpdate::rc_poll(const ParameterHandles &parameter_handles)
...
+			//This problem occurs at RC controllers which are use PPM signal on RFD 868+/900 Modems (Maybe it can be also related another types)
+
+		} else if (rc_input.channel_count ==
+			   16) { // check failsafe by channel values to detect RC loss (This statement is specific for only RF modules that still sending valid PPM signal when RC loss from ground RF)
+			for (unsigned int i = 0; i < 16; i++) {
+				if (i < 12 && rc_input.values[i] > 999 && rc_input.values[i] < 1005) {
+					signal_lost = true;
+
+				} else if (rc_input.values[i] == 0) {
+					signal_lost = true;
```
Comment (julianoes) [inline src/modules/sensors/rc_update.cpp]: What I realize now is that if you have any RC receiver with 16 channels where the last channel(s) are 0, this will cause a signal lost even though the other channels might be valid.

@bozkurthan do I see that correctly?

Comment (bozkurthan) [reply src/modules/sensors/rc_update.cpp]: Actually, I realize that PX4 logic counts correct channels every time. As far as I know, It is not possible to generate ppm signal with 0 values except RFD 868+/900 modems' problems. If the value of channel is 0 then it shouldn't be count as channel. Or channels couldn't have different min-max value. If 1 channel is between 1000-2000 another one shouldn't be between 0-1000.

Normally, it generates 1000 μs - 2000 μs ( or your arrangement ) with 300 μs pulse width from 8 channels( or your arrangement ). But when problem occurs it generates directly 1000 μs value for first 12 channels  and last 4 channels turns 0. Also, it is not related to channels' value or number of channel The trick is that there is positive pulse width between channels which causes PX4 thinks 16 channels when RC loss. Because PX4 counts pulse width between channels.

From this perspective, I checked all channels in every RC_Update.
The meaning of code:
1)Check the RC has 16 channels.
2)Check first 12 channels' value for between 1000-1005. (Because of RF changes value to this scope)
3)Check last 4 channels' value for 0.
4)Else statement. Circuit breaker.

Actually, answer of your question is in 4. step. If the value of any channel is different from 1000 -1005 (for first 12 channels) or 0 (for last 4 channels) then the failsafe can't be triggered.

Comment (julianoes) [reply src/modules/sensors/rc_update.cpp]: Oh thanks, I missed the `break`, in that case it's correct :smile:.

File: src/modules/sensors/rc_update.cpp [hunk 2]
```diff
@@ -228,6 +228,23 @@ RCUpdate::rc_poll(const ParameterHandles &parameter_handles)
 			/* signal is lost or no enough channels */
 			signal_lost = true;
 
+			//This problem occurs at RC controllers which are use PPM signal on RFD 868+/900 Modems (Maybe it can be also related another types)
+
+		} else if (rc_input.channel_count ==
```
Comment (dagar) [inline src/modules/sensors/rc_update.cpp]: You could limit this to PPM as well.

Comment (dagar) [reply src/modules/sensors/rc_update.cpp]: I haven't personally used it, but that's my understanding.

image

Doing this directly in the PPM decode might be better.

https://github.com/PX4/Firmware/blob/2fcddd9b8d36b636e84f7e6c57f13904af79e430/platforms/nuttx/src/px4/stm/stm32_common/hrt/hrt.c#L447-L595

Comment (bkueng) [reply src/modules/sensors/rc_update.cpp]: I agree, it would be better doing that in the PPM decoder.

Comment (julianoes) [reply src/modules/sensors/rc_update.cpp]: But the change seems quite specific to fix exactly one corner case, therefore I think it's worth it.

Comment (dagar) [reply src/modules/sensors/rc_update.cpp]: I'm not sure what you mean. It's a corner case that applies to one specific PPM receiver.

Comment (julianoes) [reply src/modules/sensors/rc_update.cpp]: Yes but it's good for that one corner case :smile:.

Comment (julianoes) [reply src/modules/sensors/rc_update.cpp]: My take is that this is good for this corner case, and it doesn't cause any harm so it's worthwhile to be merged.

**Comment by julianoes** [comment]
@bkueng any objections to get this in?

**Comment by bkueng** [comment]
Actually yes, I don't like this special case that is protocol-specific in the generic code path for RC.
The least required for me is make it conditional on PPM.

**Comment by FlavioTonelli** [comment]
I can't get why we need to add a new logic to identify such a fail. The RC_FAILS_THR and RC_MAP_FAILSAFE parameters shall be sufficient to cover that case. Am I wrong?

**Comment by julianoes** [comment]
@FlavioTonelli if you have it configured correctly, yes. If not, then this can save you.

**Comment by julianoes** [comment]
@bkueng rebased and made specific to PPM, please review again.
