### PR TITLE
commander state machine fix preflight and prearm error

### LINKED ISSUE #9155: System is arming (or thinks it is arming) even with Critical warnings (specifically "MAG SENSORS INCONSISTENT")
PX4 1.7.3, installed on a Pixracer, using QGC v3.3.0.  The pixracer is sitting on my desk connected to QGC over USB.  I have a valid GPS fix.  I try to Arm and it seems to let me even with the following Critical warnings:

image
image

Is this right?

### PR DESCRIPTION
**Pull request by dagar**
-  fixes #9155

There were many issues. The most important immediate issue is that preflight checks haven't been blocking arming. Additionally many little annoying edge cases I've experienced finally make sense to me where you might not be provided appropriate (or any) feedback trying to arm.

There's still a lot more to do here, but this restores a level of sanity. The next steps from my perspective would be removing the actual sensor check calls from the state machine and centralizing all of it on the commander side. Then commander would simple pass the appropriate flags into a much simpler generated (and documented) state machine.

### CODE REVIEW

**Comment by dagar** [comment]
@PX4/testflights please bench test on a couple different systems.

Verify things like...
 - safety button works as expected for arming or preventing arming
 - low battery prevents arming
 - test the COM_ARM_WO_GPS parameter
 - test the COM_ARM_MIS_REQ parameter
 - try to arm with a bogus compass setup (uncalibrated, external rotated 90 degrees, etc)

**Comment by dagar** [comment]
TODO (possibly after this PR):

 - review preflight, prearm, and all the state machines in general with respect to calibration. I believe there are currently some holes.
 - review HIL and try to extract and centralize all HIL specific behaviour changes. The state machines themselves (and eventually all of commander) could be completely oblivious to HIL.

**Comment by Avysuarez** [comment]
Test with pixhawk 2.1:
1; safety button works as expected for arming or preventing arming.
Not arming.
2;low battery prevents arming.
Not arming, low battery message.
3; test the COM_ARM_WO_GPS parameter.
Not arming. position reject message
4;test the COM_ARM_MIS_REQ parameter.
Not arming
5; try to arm with a bogus compass setup (uncalibrated, external rotated 90 degrees, etc)
Not arming.
6; try to arm with USB connected.
Not arming.

File: src/modules/commander/PreflightCheck.cpp [hunk 1]
```diff
@@ -448,6 +449,47 @@ static bool airspeedCheck(orb_advert_t *mavlink_log_pub, bool optional, bool rep
...
+static bool powerCheck(orb_advert_t *mavlink_log_pub, bool report_fail, bool prearm)
+{
+	bool success = true; // start with a pass and change to a fail if any test fails
+
+	if (prearm) {
+		int system_power_sub = orb_subscribe(ORB_ID(system_power));
+
+		system_power_s system_power = {};
+
+		if (orb_copy(ORB_ID(system_power), system_power_sub, &system_power) == PX4_OK) {
```
Comment (julianoes) [inline src/modules/commander/PreflightCheck.cpp]: If there is no system power update, this check will just pass. As I understand it, there will always be one `orb_copy` and therefore we would copy an `avionics_power_rail_voltage` of `0` and fail anyway.

File: src/modules/commander/PreflightCheck.cpp [hunk 2]
```diff
@@ -448,6 +449,47 @@ static bool airspeedCheck(orb_advert_t *mavlink_log_pub, bool optional, bool rep
 	return success;
 }
 
+static bool powerCheck(orb_advert_t *mavlink_log_pub, bool report_fail, bool prearm)
+{
+	bool success = true; // start with a pass and change to a fail if any test fails
+
+	if (prearm) {
```
Comment (julianoes) [inline src/modules/commander/PreflightCheck.cpp]: I'd prefer the structure like this:
```
if (!prearm) {
    // Ignore power check after arming.
    return true;
}
...
```

File: src/modules/commander/PreflightCheck.cpp [hunk 3]
```diff
@@ -570,12 +612,12 @@ static bool ekf2Check(orb_advert_t *mavlink_log_pub, bool optional, bool report_
 }
 
 bool preflightCheck(orb_advert_t *mavlink_log_pub, bool checkSensors, bool checkAirspeed, bool checkRC, bool checkGNSS,
-		    bool checkDynamic, bool isVTOL, bool reportFailures, bool prearm, hrt_abstime time_since_boot)
+		    bool checkDynamic, bool checkPower, bool isVTOL, bool reportFailures, bool prearm, const hrt_abstime &time_since_boot)
```
Comment (julianoes) [inline src/modules/commander/PreflightCheck.cpp]: This list of bools needs to go away in the future, that's super error-prone. A `struct` containing the bools would already be better.

File: src/modules/commander/PreflightCheck.cpp [hunk 4]
```diff
@@ -602,13 +644,16 @@ bool preflightCheck(orb_advert_t *mavlink_log_pub, bool checkSensors, bool check
...
+
 		/* check all sensors, but fail only for mandatory ones */
 		for (unsigned i = 0; i < max_optional_mag_count; i++) {
 			bool required = (i < max_mandatory_mag_count);
 			int device_id = -1;
 
-			if (!magnometerCheck(mavlink_log_pub, i, !required, device_id, reportFailures) && required) {
+			if (!magnometerCheck(mavlink_log_pub, i, !required, device_id, (reportFailures && !mag_fail_reported)) && required) {
 				failed = true;
+				mag_fail_reported = true;
```
Comment (julianoes) [inline src/modules/commander/PreflightCheck.cpp]: The `mag_fail_reported` flag doesn't do anything as I understand it. Since `max_mandatory_mag_count` is 1, only the first check is required. After that `(reportFailures && !mag_fail_reported)) && required` evaluates to `false` anyway.

File: src/modules/commander/state_machine_helper.cpp [hunk 5]
```diff
@@ -129,65 +136,33 @@ transition_result_t arming_state_transition(vehicle_status_s *status, const batt
...
-			} else {
-				prearm_ret = last_prearm_ret;
 			}
 		}
 
-		/*
-		 * Perform an atomic state update
-		 */
-#ifdef __PX4_NUTTX
-		irqstate_t flags = px4_enter_critical_section();
```
Comment (julianoes) [inline src/modules/commander/state_machine_helper.cpp]: What's the reason that all this is removed?

File: src/modules/commander/state_machine_helper.cpp [hunk 6]
```diff
@@ -1035,45 +931,91 @@ void reset_link_loss_globals(actuator_armed_s *armed, const bool old_failsafe, c
...
 		}
+
+		prearm_ok = false;
 	}
 
-	/* report once, then set the flag */
-	if (reportFailures && !prearm_ok) {
-		status_flags->condition_system_prearm_error_reported = true;
+	// Arm Requirements: authorization
+	// check last, and only if everything else has passed
```
Comment (julianoes) [inline src/modules/commander/state_machine_helper.cpp]: Makes sense.

File: src/modules/commander/PreflightCheck.cpp (hunk 1 above)
Comment (dagar) [reply src/modules/commander/PreflightCheck.cpp]: I added a time elapsed check as a workaround, which should be fine for now, but still isn't ideal. After this PR I was thinking about centralizing the arming requirements checks. We can make system_power explicitly required or not.

File: src/modules/commander/PreflightCheck.cpp (hunk 2 above)
Comment (dagar) [reply src/modules/commander/PreflightCheck.cpp]: Sure, that works for me.

File: src/modules/commander/PreflightCheck.cpp (hunk 3 above)
Comment (dagar) [reply src/modules/commander/PreflightCheck.cpp]: Completely agree. I was going to start using vehicle_status_flags and vehicle_status after this PR.

File: src/modules/commander/PreflightCheck.cpp (hunk 4 above)
Comment (dagar) [reply src/modules/commander/PreflightCheck.cpp]: It should prevent the repetition of 

    PREFLIGHT FAIL: MAG 0 UNCALIBRATED
    PREFLIGHT FAIL: MAG 1 UNCALIBRATED
    PREFLIGHT FAIL: MAG 2 UNCALIBRATED

Since you can only calibrate them in bulk, I didn't see the point in reporting more than a single line.

File: src/modules/commander/state_machine_helper.cpp (hunk 5 above)
Comment (dagar) [reply src/modules/commander/state_machine_helper.cpp]: Why is it needed? The state machine isn't grabbing new system data in this section. If it was important we'd also need an equivalent on Linux and QuRT.

Comment (julianoes) [reply src/modules/commander/state_machine_helper.cpp]: I don't know. But ok makes sense then.

File: src/modules/commander/PreflightCheck.cpp (hunk 4 above)
Comment (julianoes) [reply src/modules/commander/PreflightCheck.cpp]: But if you only report for mandatory devices then you don't need the reported flag, `required` should be enough.

**Comment by AlexisTM** [comment]
NOTE: With the 1.7.2 release, I sometimes cannot arm because of the following error: `PREFLIGHT FAIL: ACCEL SENSORS INCONSISTENT - CHECK CALIBRATION`. 

This is on a Pixhawk 1, with only one IMU.

**Comment by Avysuarez** [comment]
@dagar 

> Did you see any situations where arming was blocked and no explanation was given? 

No, I didn't see any, in all tests when there were no conditions to arm I received messages with the explanation.

> Did you see any situations where there was a mavlink critical message (pop up in the yellow box), but arming was allowed to complete?

No, I didn't see any. When I got mavlink critical messages such as low battery, gps not ready to takeoff, etc, arming was not allowed.

File: src/modules/commander/PreflightCheck.cpp (hunk 4 above)
Comment (dagar) [reply src/modules/commander/PreflightCheck.cpp]: It still reports uncalibrated for optional devices. I find the entire thing more convoluted than necessary. It could almost be refactored into a template for all types.

**Comment by dagar** [comment]
We need to verify this doesn't break HIL.

**Comment by RomanBapst** [comment]
@dagar Tested in HIL with multicopter and did not have any issues.

**Comment by dagar** [comment]
This needs a non-trivial rebase.

File: src/modules/commander/PreflightCheck.cpp [hunk 7]
```diff
@@ -602,13 +713,16 @@ bool preflightCheck(orb_advert_t *mavlink_log_pub, bool checkSensors, bool check
...
 
+		bool mag_fail_reported = false;
+
 		/* check all sensors, but fail only for mandatory ones */
 		for (unsigned i = 0; i < max_optional_mag_count; i++) {
 			bool required = (i < max_mandatory_mag_count);
 			int device_id = -1;
 
-			if (!magnometerCheck(mavlink_log_pub, i, !required, device_id, reportFailures) && required) {
+			if (!magnometerCheck(mavlink_log_pub, i, !required, device_id, (reportFailures && !failed && !mag_fail_reported)) && required) {
```
Comment (julianoes) [inline src/modules/commander/PreflightCheck.cpp]: Oh, I think I get this now. I was reading the brackets the wrong way.

**Comment by dagar** [comment]
Only reporting a single critical message at a time is intentional. Preflight checks run first, prearm (safety button) only runs at all if preflight passes.

In the case of sensors this seemed okay because the periodic preflight run and report is forced after a calibration. So you'd see the next sensor error after resolving the MAG before you even tried to arm again. I'm trying to find a line where we only report the most important thing for the user to act on, but balanced against having to attempt arming again before getting the next error.

Ideally I want to get to the point where the GCS won't even let you arm without resolving these issues first.

**Comment by mhkabir** [comment]
Okay makes sense. I tested some other combinations, and this seems to work as expected! 

I vote to merge this now and continue working on user experience incrementally.

**Comment by dagar** [comment]
Rebased on master again. Last call for testing.

**Comment by dagar** [comment]
Thanks everyone.

**Comment by potaito** [comment]
@dagar 
I am a bit late to the party, but can you clarify something? Before, the power check would only run if the 3.3V and 5.0V power rails were above 0.0V:
https://github.com/PX4/Firmware/commit/729c98d9e290ae27da1671ec72f1549b73dab20e#diff-20f2c9d76df9330422532b87ab964f86L222

In the new preflight check, this `>0.0` condition has been removed:
https://github.com/PX4/Firmware/blob/df042ab20e5ab1df43a322eacdb0e189c1b01652/src/modules/commander/PreflightCheck.cpp#L496-L513

Is there a specific reason for that? 

I am asking because I have a system here that is always showing 0.0V on both rails and now the preflight check fails obviously.

**Comment by dagar** [comment]
The structure is a bit different now because the avionics power rail voltage is no longer passed into the arming state machine directly as a float. Now it's only checked after the system_power message publishes, so we don't need the > 0.0 hack.

There's also the power circuit breaker that can be used to explicitly ignore these checks.
