### PR TITLE
frsky_telemetry improved com port init (fix #9783), minor refactor

### LINKED ISSUE #9783: frsky_telemetry using hardware flow control com port on pixhawk (solution)
Using frsky_telemetry (D TYPE) with output on a port with hw flow control (i.e. /dev/ttyS1) does not work. 
Attach frsky_telemetry with frsky_telemetry start -d /dev/ttyS1 to a type D receiver it produces "INFO [frsky_telemetry] sending frSky D type telemetry" but no data flows on the channel.
Notice: In tested configuration mavlink telemetry was stopped at /dev/ttyS1 before frsky device driver started.
The needs of using ttyS1 due to SYSCOMPANION = mavesp and serial 4 used for tfmini ranger. This way only serial line available is ttyS1 on pxhawk hardware.

Solution:
Add this lines to frsky_telemetry.cpp SOLVE the problem
... just after:
        /* Disable output post-processing */
        uart_config->c_oflag &= ~OPOST;
..in static int sPort_open_uart
.. add:

```
uart_config->c_cflag |= (CLOCAL | CREAD); /* ignore modem controls */
uart_config->c_cflag &= ~CSIZE;
uart_config->c_cflag |= CS8; /* 8-bit characters */
uart_config->c_cflag &= ~PARENB; /* no parity bit */
uart_config->c_cflag &= ~CSTOPB; /* only need 1 stop bit */
uart_config->c_cflag &= ~CRTSCTS; /* no hardware flowcontrol */
```

```
/* setup for non-canonical mode */
uart_config->c_iflag &= ~(IGNBRK | BRKINT | PARMRK | ISTRIP | INLCR | IGNCR | ICRNL | IXON);
uart_config->c_lflag &= ~(ECHO | ECHONL | ICANON | ISIG | IEXTEN);
```

```
/* fetch bytes as they become available */
uart_config->c_cc[VMIN] = 1;
uart_config->c_cc[VTIME] = 1;
```

### PR DESCRIPTION
**Pull request by gianni-carbone**
Change code setup for the serial port used for sending data.
Fix the problem using serial port with hardware flow control, for example /dev/ttyS1 in pixhawk hardware.
It could be useful if you have to use that port when others are used by attached devices (i.e. esp telemetry on telem2 and tfmini ranger on serial 4)

fixes issue #9783

Some code rework: 
- errx( replaced by PX4_INFO( and printf in show status code
- added sent packet counter
- used phisical port and packet sent counter now shown in "status" output

### CODE REVIEW

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 1]
```diff
@@ -676,21 +703,30 @@ int frsky_telemetry_main(int argc, char *argv[])
 		if (thread_running) {
 			switch (frsky_state) {
 			case SCANNING:
-				errx(0, "running: SCANNING");
-				break;
-
+        PX4_INFO("running: SCANNING");
+        printf("port: %s\n", device_name);
```
Comment (bkueng) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: can you use PX4_INFO instead of printf?

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 2]
```diff
@@ -199,9 +216,6 @@ static void usage()
  */
 static int frsky_telemetry_thread_main(int argc, char *argv[])
 {
-	/* Default values for arguments */
-	const char *device_name = "/dev/ttyS6"; /* USART8 */
```
Comment (bkueng) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: This can lead to a memory access violation with the following steps:
```
frsky_telemetry start -d /dev/some/device
frsky_telemetry stop
frsky_telemetry start  <- accesses `device_name` which was freed via `frsky_telemetry stop`.
```
It can be fixed by initializing device_name here:
```
device_name = "/dev/ttyS6"; /* USART8 */
```
And initializing it with NULL above, and also to be sure, setting it to NULL when the main thread exits.

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp (hunk 1 above)
Comment (gianni-carbone) [reply src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: ok done

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp (hunk 2 above)
Comment (gianni-carbone) [reply src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: WIP

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 3]
```diff
@@ -650,7 +685,7 @@ int frsky_telemetry_main(int argc, char *argv[])
 		while (!thread_running) {
 			usleep(200);
 		}
-
```
Comment (LorenzMeier) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: unnecessary whitespace added.

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 4]
```diff
@@ -627,6 +660,8 @@ static int frsky_telemetry_thread_main(int argc, char *argv[])
  */
 int frsky_telemetry_main(int argc, char *argv[])
 {
+
```
Comment (LorenzMeier) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: Unnecessary whitespace change.

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 5]
```diff
@@ -667,30 +702,40 @@ int frsky_telemetry_main(int argc, char *argv[])
 			usleep(1000000);
 			warnx(".");
 		}
-
```
Comment (LorenzMeier) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: Whitespace.

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 6]
```diff
@@ -667,30 +702,40 @@ int frsky_telemetry_main(int argc, char *argv[])
...
+		
 		warnx("terminated.");
+		device_name = NULL;
 		exit(0);
 	}
 
 	if (!strcmp(argv[1], "status")) {
 		if (thread_running) {
 			switch (frsky_state) {
+
```
Comment (LorenzMeier) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: Whitespace.

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 7]
```diff
@@ -667,30 +702,40 @@ int frsky_telemetry_main(int argc, char *argv[])
...
 			switch (frsky_state) {
+				
 			case SCANNING:
-				errx(0, "running: SCANNING");
+				PX4_INFO("running: SCANNING");
+				PX4_INFO("port: %s\n", device_name);
+				exit(0);
 				break;
-
+
```
Comment (LorenzMeier) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: Whitespace.

File: src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp [hunk 8]
```diff
@@ -667,30 +702,40 @@ int frsky_telemetry_main(int argc, char *argv[])
...
 
 	if (!strcmp(argv[1], "status")) {
 		if (thread_running) {
 			switch (frsky_state) {
+				
 			case SCANNING:
-				errx(0, "running: SCANNING");
+				PX4_INFO("running: SCANNING");
+				PX4_INFO("port: %s\n", device_name);
+				exit(0);
```
Comment (LorenzMeier) [inline src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: would be better to use return 0 here as that will make this driver Linux-compatible.

Comment (gianni-carbone) [reply src/drivers/telemetry/frsky_telemetry/frsky_telemetry.cpp]: @LorenzMeier ... sorry. Used 'make format' now. Changed exit(0) with return 0. Tested with D type telemetry it works OK. Tested start -d \dev\ttyS1, status, stop then start again. Thanks @bkueng for suggestion.

**Comment by LorenzMeier** [comment]
Squashed and merged. Thanks!
