### PR TITLE
smooth takeoff - Support smooth takeoff triggered by jerk setpoint

### LINKED ISSUE #11452: Takeoff not responding properly in position control
@MaEtUgR I create this Issue to keep track of what we discussed on slack.

**Describe the bug**
While armed in position control with the throttle stick low, the flight task generates a negative setpoint. When now the user moves the throttle stick above 50%, the setpoint has to go positive before triggering the smooth takeoff. However, with the dynamics of the smooth flight tasks, this takes and depends of some parameters such as the max down velocity, vertical acceleration and jerk limitations.
I see two ways to solve that:
1. Make the flight task aware of the current state (the flight task will then not output a downward sertpint while on ground)
2. Modify the constraint in mc_pos_control and feet it back to the flight task (I tried that on a branch)
The problem is that both solutions introduce a feedback to the flight task and I know that @stifael wanted to avoid that. Do you have an other solution? 

**To Reproduce**
In position control mode (using a smoothing FlightTask with low vertical acceleration and jerk)
Set the throttle stick to low
Arm and wait a few seconds
Raise the stick above 50%, it will take some time before taking off

To avoid this issue :
- Use a spring-loaded throttle stick or center the throttle stick before arming and use an arm switch
- Arm and directly center the throttle stick

**Expected behavior**
The drone should takeoff as soon as the throttle stick is above 50%

**Log Files and Screenshots**
takeoff_delay

**Proposed solution**
I tried the 2nd solution proposed in the description and limit the downward velocity constraint while the vehicle is on ground, here is the result:
smooth_takeoff_refactor

@Stifael I know that you want to avoid having feedback to the FlightTask, but I can't find a cleaner solution. Let's discuss that here.

### PR DESCRIPTION
**Pull request by bresch**
fixes #11452 

**Test data / coverage**
Tested in SITL
jerk-triggered_takeoff

**Describe problem solved by the proposed pull request**
A (hard to predict) delay before takeoff was present on all the non spring-loaded remotes while using the `SmoothVelocity` position sub mode. This PR enables a full reset of the `ManualSmoothVel` FlightTask by adding a jerk-based check to trigger "smooth takeoff" in `mc_pos_control_main`.
Takeoff is now triggered as soon as the throttle stick is above 50%.

**Describe possible alternatives**
Setting the `vel_down` constraint to 0 while on ground.

### CODE REVIEW

**Comment by bresch** [comment]
FYI @RomanBapst

**Comment by bresch** [comment]
Tested on a F450:
f450-takeoff_jerk

@PX4/testflights Could you test that PR with the following parameters please:
- `MPC_POS_MODE` = 3 (smooth velocity) and 1 (default smooth)
- `MPC_ACC_UP_MAX` = 2 m/s^2

File: src/lib/FlightTasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp [hunk 1]
```diff
@@ -65,7 +65,8 @@ class FlightTaskManualPositionSmoothVel : public FlightTaskManualPosition
 private:
 
 	enum class Axes {XY, XYZ};
-	void reset(Axes axes);
+	void reset(Axes axes, bool force_z_zero =
```
Comment (bkueng) [inline src/lib/FlightTasks/tasks/ManualPositionSmoothVel/FlightTaskManualPositionSmoothVel.hpp]: Can you reformat this to the usual method documentation to avoid the weird line-break?
```suggestion
	 /** 
	  * Reset the required axes. when force_z_zero is set to true, the z derivatives are set to sero and not to the estimated states
	  */
	void reset(Axes axes, bool force_z_zero = false);
```

**Comment by jorge789** [comment]
Pixhawk Pro and PixRacer was tested.
**Observations on PR11460:** Upon landing, _while PR11460 was loaded_, the vehicle did not disarm automatically.
**Observations on Master**: _While using Master_, UAV did not disarm on an uneven surface but did disarm fast on an even surface.

https://review.px4.io/plot_app?log=ba159bea-a29e-4d12-9a7f-dbf0645af8f7

**Note:** Same behavior from the Pixhawk Pro applies to PixRacer. 

https://review.px4.io/plot_app?log=acfcf065-f22b-4878-8e0c-24db50021143

**Comment by bresch** [comment]
@jorge789 Thanks for the tests! The landing issue is is unrelated to that PR.
Apparently, the drone enters the landed state on ground but directly goes back to `ground_contact` -> `maybe_landed` -> `landed` and loops again:
landed_oscillation
@MaEtUgR How is it possible that the drone exits the landed state if freefall is not detected?
Here is the related log: https://review.px4.io/plot_app?log=ba159bea-a29e-4d12-9a7f-dbf0645af8f7

**Comment by bresch** [comment]
@bkueng Can you review again?
The logic works as expected on the logs provided by the test team:
takeoff_jerk_detection
We can see that the takeoff is directly triggered as soon as the throttle stick reaches 50%.

**Comment by bresch** [comment]
@bkueng Fixed and squashed

**Comment by bresch** [comment]
@PX4/testflights I found the root cause of why the vehicle didn't disarm on ground and fixed it  I tested on my vehicle and looks good to go.
Can you redo a quick test with the parameters I mentioned previously and see if the landing works properly? Thanks!

**Comment by Tony3dr** [comment]
> @PX4/testflights I found the root cause of why the vehicle didn't disarm on ground and fixed it I tested on my vehicle and looks good to go.
> Can you redo a quick test with the parameters I mentioned previously and see if the landing works properly? Thanks!

@bresch Great! We have rain today, we should be able to test the PR by tomorrow. We will let you know how it goes.

**Comment by jorge789** [comment]
Tested on pixracer v4.
Note: The vehicle landed correctly and disarmed in two seconds and without any jump as before and for everything else the vehicle flew vastly.

https://review.px4.io/plot_app?log=a04d39c2-1fc2-4243-b3c1-319a1d1ca03a

**Comment by bresch** [comment]
@jorge789 Awesome, thanks.
@bkueng Can we merge that now?

File: src/modules/mc_pos_control/mc_pos_control_main.cpp [hunk 2]
```diff
@@ -1047,6 +1046,8 @@ MulticopterPositionControl::check_for_smooth_takeoff(const float &z_sp, const fl
 
 		// takeoff was initiated through velocity setpoint
 		_smooth_velocity_takeoff = PX4_ISFINITE(vz_sp) && vz_sp < -0.1f;
+		bool jerk_triggered_takeoff = PX4_ISFINITE(jerk_sp) && jerk_sp < -FLT_EPSILON;
```
Comment (bkueng) [inline src/modules/mc_pos_control/mc_pos_control_main.cpp]: correct now :)
