### PR TITLE
i2c_spi_buses: add '-q' for quiet startup flag

### LINKED ISSUE #14946: [RFC] Drivers should not fail silently
This is place holder for discussing the messages from driver.

Currently there is no output on a failure which makes verification of a system not possible.

### PR DESCRIPTION
**Pull request by bkueng**
And enable for optional board sensors.

E.g:
```
nsh> ist8310 start -X
WARN  [SPI_I2C] ist8310: no instance started (no device on bus?)
```

Fixes  #14946

@davids5 does this work for you?

### CODE REVIEW

File: boards/px4/fmu-v5/init/rc.board_sensors [hunk 1]
```diff
@@ -6,10 +6,10 @@
 adc start
 
 # Internal SPI bus ICM-20602
-icm20602 -s -R 2 start
+icm20602 -s -R 2 -q start
 
 # Internal SPI bus ICM-20689
-icm20689 -s -R 2 start
+icm20689 -s -R 2 -q start
```
Comment (dagar) [inline boards/px4/fmu-v5/init/rc.board_sensors:12]: I believe the icm20689 is on all fmu-v5s.

**Comment by dagar** [comment]
I was going to suggest printing all the attempted buses (and optionally i2c addresses) tried, but I suppose that will make a mess of the intended cases.

File: ROMFS/px4fmu_common/init.d/rcS [hunk 2]
```diff
@@ -198,8 +198,8 @@ else
 	#
 	# Start system state indicator.
 	#
-	rgbled start -X
-	rgbled_ncp5623c start -X
+	rgbled start -X -q
```
Comment (dagar) [inline ROMFS/px4fmu_common/init.d/rcS:201]: We should think about gathering up and centralizing all of these external optional I2C things. Maybe initially we could hide them all behind a single parameter for optionally probing external I2C buses?

**Comment by dagar** [comment]
Merged in current master and added `-q` to all the optional external i2c peripherals in rc.sensors.
