### PR TITLE
Fix warning on do jump

### LINKED ISSUE #13592: Error message "unable to read from microSD" when flying a mission with "jump to item"
**Describe the bug**
When flying a mission on a VTOL with a "jump to item" in it, it does what it is supposed to do (go back to selected item and then continue the mission from there on again), but it gives the following error message every time it reaches the "jump to item" waypoint:
image

https://review.px4.io/plot_app?log=e3b60ca9-d232-46d3-99f4-65220f2360b2

### PR DESCRIPTION
**Pull request by julianoes**
Fixes #13592.

### CODE REVIEW

File: src/modules/mavlink/mavlink_mission.cpp [hunk 1]
```diff
@@ -305,19 +305,19 @@ void
...
 {
 	mission_item_s mission_item = {};
-	bool read_success = false;
+	int read_result = 0;
 
 	switch (_mission_type) {
 
 	case MAV_MISSION_TYPE_MISSION: {
-			read_success = dm_read(_dataman_id, seq, &mission_item, sizeof(mission_item_s)) == sizeof(mission_item_s);
+			read_result = dm_read(_dataman_id, seq, &mission_item, sizeof(mission_item_s)) == sizeof(mission_item_s);
```
Comment (MaEtUgR) [inline src/modules/mavlink/mavlink_mission.cpp:313]: Now I'm confused. Before this commit it was `bool = size_t == size_t`
With this commit it became `int = size_t == size_t` which is according to my understanding an implicit cast from bool (result of == operator) to int.
So if I'm not mistaken this commit does the opposite of what it intended to do.
We should probably set the parentheses differently for the operations to be visible more clearly.

Comment (MaEtUgR) [reply src/modules/mavlink/mavlink_mission.cpp:313]: Here's my suggestion to make this more clear: https://github.com/PX4/PX4-Autopilot/pull/19653

Comment (julianoes) [reply src/modules/mavlink/mavlink_mission.cpp:313]: Oops.
