### PR TITLE
fixed wing offboard attitude setpoint fix

### LINKED ISSUE #5927: Fixed Wing Offboard Ignores Attitude Setpoint
The fixed wing controller ignores attitude setpoints in offboard mode. I originally filed this over on mavros, but later found the problem in the px4 firmware (https://github.com/mavlink/mavros/issues/630)

I've tentatively traced it to the fixed-wing attitude controller which generates attitude targets from the manual inputs whenever climb rate control is disabled (line 959, https://github.com/PX4/Firmware/blob/master/src/modules/fw_att_control/fw_att_control_main.cpp)

adding another condition for offboard mode fixes it, but I'm not familiar enough with the controller structure to know if that is likely to introduces problems elsewhere.

Original:
`if (!_vcontrol_mode.flag_control_climb_rate_enabled) {`

With additional condition:
`if (!_vcontrol_mode.flag_control_climb_rate_enabled && !_vcontrol_mode.flag_control_offboard_enabled) {`

### PR DESCRIPTION
**Pull request by aivian**
Fix #5927 where attitude setpoints from offboard were being overwritten by the RC channels due to some missing flags.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice, thanks!

**Comment by LorenzMeier** [comment]
@tumbili @dagar Can you review for potential side-effects to standard operation? Diff looked good otherwise.

File: src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp [hunk 1]
```diff
@@ -2338,14 +2338,20 @@ FixedwingPositionControl::task_main()
...
-				/* lazily publish the setpoint only once available */
-				if (_attitude_sp_pub != nullptr) {
-					/* publish the attitude setpoint */
-					orb_publish(_attitude_setpoint_id, _attitude_sp_pub, &_att_sp);
-
-				} else if (_attitude_setpoint_id) {
-					/* advertise and publish */
-					_attitude_sp_pub = orb_advertise(_attitude_setpoint_id, &_att_sp);
+				if (!(_control_mode.flag_control_offboard_enabled &&
+				      !(_control_mode.flag_control_position_enabled ||
```
Comment (dagar) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: This doesn't cover altitude control mode where position, velocity, acceleration are off.

Comment (dagar) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: It might be a bit easier to read like this.

    !(A && !B) == !A || B

Comment (aivian) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: I'll confess to some unfamiliarity with the flag structure, but wouldn't altitude control mode trigger climb rate enabled?

Comment (dagar) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: Yes, you can see them here - https://github.com/PX4/Firmware/blob/master/src/modules/commander/commander.cpp#L3630

So isn't this wrong for altitude control mode?

Comment (aivian) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: I think this will work for altitude control. tecs will provide a pitch setpoint, so the L1 controller should publish. The climb rate control flag will prevent the attitude controller from overwriting from the sticks. I'm not sure where the roll command comes from here, but I don't think this update changes that.

Am I missing something there? I'm away from my HiL setup right now so I can't test it.

Comment (dagar) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: For altitude control mode we need fw_pos_ctrl to publish an attitude setpoint when position, velocity, acceleration flags are false. The roll comes from the stick input, but currently that's handled in fw_pos_ctrl.

What about other offboard setpoints with position or altitude?

**Comment by yzzir** [comment]
I'm a little confused on the changes.  Isn't the fw position controller code changes to control when to publish the attitude setpoint needed only to prevent the fw position controller from overwriting the published attitude setpoint when a MAVLINK_MSG_ID_SET_ATTITUDE_TARGET message is received?  Otherwise wouldn't the same code in the mc position controller also be incorrect?

File: src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp (hunk 1 above)
Comment (aivian) [inline src/modules/fw_pos_control_l1/fw_pos_control_l1_main.cpp]: Ah, yeah that will need a check on the climb rate control flag. I *think* that the other offboard modes should set control_mode flags such that it'll work with a check on climb rate.

I'm having all kinds of trouble with the HiL right now so I can't test unfortunately. Will report back when I get it working.

**Comment by AndreasAntener** [comment]
I checked the setpoint publication conditions and they are actually the same now for MC and FW.

In MC we have:
`! ( offboard && ! ( position || velocity || acceleration )`

Which can be written as (and should be changed into that form for readability):
`! offboard || ( position || velocity || acceleration )` (brackets are also not necessary anymore)

So i think this is good to go.

**Comment by dagar** [comment]
I agree it looks correct now. Is anyone in a position to actually test this?

Build failure looks like a semaphore issue, restarted.

**Comment by aivian** [comment]
I got my HiL working again, so I can test in sim, but not flight. Do you have suggested cases?

**Comment by dagar** [comment]
Offboard mode with a range of different setpoint types. Quickly flip through stabilized, altitude and position control as well.

**Comment by AndreasAntener** [comment]
@aivian note that #6537 just got merged, which means this would require a rebase and a quick change in the state machine helper to allow fixed-wing going into offboard again.

**Comment by aivian** [comment]
I think I got the rebase done properly. For testing I've re-enabled offboard by simply removing the check for vehicle type. I'm not sure if that's the right solution or if this thread/patch is the right place to address it.

**Comment by aivian** [comment]
Ok, report on modes:

stabilized: works fine
position: lateral stick commands turn rate, throttle stick commands speed, pitch stick commands climb rate

OFFBOARD modes (I'm not sure how may of these should/ever worked)
accel:
input: sinusoidal y acceleration magnitude 5.0 (m/s?)
response: slightly left turn, no sinusoid, no response from sticks

rates:
input: zero rates on all axes
response: immediately rolls inverted and tries to crash

attitude:
input: sinusoidal roll angle command, 30 degree amplitude
response: tracks sinusoidal input well

local position:
input: (0, 0, 0)
output: the aircraft flies as if it is in position control mode

**Comment by dagar** [comment]
Isn't this ignoring offboard position setpoints?

**Comment by dagar** [comment]
This actually needs a tiny change here to allow offboard for FW. https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L456

You can either add that here, or I'll make the change after this is merged. It's something I only recently changed in master.

**Comment by aivian** [comment]
Just remove the check for rotary wing? If that's all it is I can add it super-quick, my local version already has that done so I could test.

**Comment by dagar** [comment]
Yes, exactly. https://github.com/PX4/Firmware/commit/d0b188f585e08d1f391d7360b640c6194f3e1acf

**Comment by aivian** [comment]
done

**Comment by dagar** [comment]
Thanks!
