### PR TITLE
ak09916: fail if device is not found

### LINKED ISSUE #11844: AK09916 reports device when not connected
It seems that the new driver from https://github.com/PX4/Firmware/pull/11837 reports the device being there even if it is not connected.

@jzazbert do you know why that is?

Booting the PH21 without external mag connected gives me the following console out anyway:
```
AK09916 on I2C bus 1 at 0x0c (bus: 100 KHz, max: 400 KHz)
```

### PR DESCRIPTION
**Pull request by julianoes**
This should fix the case where the driver initializes even though the device is not found. The change changes the behavior to return ERROR if the whoami call fails several times instead of returning OK.

Also, the reset() and thus probe() calls are moved before initializing
the ringbuffer and device name.

Could fix #11844.

This only compiles, @AndreasAntener could you test this please?

### CODE REVIEW

**Comment by dagar** [comment]
`I2C::init()` calls probe().

File: src/drivers/magnetometer/ak09916/ak09916.hpp [hunk 1]
```diff
@@ -139,6 +139,7 @@ class AK09916 : public device::I2C
 	void read_block(uint8_t reg, uint8_t *val, uint8_t count);
 
 	int reset(void);
+	int probe(void);
```
Comment (dagar) [inline src/drivers/magnetometer/ak09916/ak09916.hpp]:
```suggestion
	int probe() override;
```

File: src/drivers/magnetometer/ak09916/ak09916.cpp [hunk 2]
```diff
@@ -583,8 +583,7 @@ AK09916::write_reg(uint8_t reg, uint8_t value)
 int
 AK09916::reset(void)
 {
-	// First initialize it to use the bus
-	int rv = setup();
+	int rv = probe();
```
Comment (dagar) [inline src/drivers/magnetometer/ak09916/ak09916.cpp]: I would remove the reset logic from probe().

File: src/drivers/magnetometer/ak09916/ak09916.hpp (hunk 1 above)
Comment (julianoes) [reply src/drivers/magnetometer/ak09916/ak09916.hpp]: I agree I was just being consistent :)

File: src/drivers/magnetometer/ak09916/ak09916.cpp (hunk 2 above)
Comment (julianoes) [reply src/drivers/magnetometer/ak09916/ak09916.cpp]: I would too but I wanted to make minimal changes.

File: src/drivers/magnetometer/ak09916/ak09916.hpp (hunk 1 above)
Comment (jkflying) [reply src/drivers/magnetometer/ak09916/ak09916.hpp]: Maybe it would be good to add `-Wsuggest-override`/`-Werror=suggest-override` to make sure we are consistent here?

**Comment by LorenzMeier** [comment]
@AndreasAntener Could you please test so we're unblocked on this? @julianoes @bkueng do we not have any hardware on hand that has this part?

**Comment by AndreasAntener** [comment]
Great, I'll check! (I started moving it to the device interface but other things came in between...)

**Comment by LorenzMeier** [comment]
Awesome, thank you so much for the swift testing!
