### PR TITLE
mavlink: fix potential busy loop upon USB disconnect

### LINKED ISSUE #14600: logger watchdog triggered on FW fmu-v5
https://logs.px4.io/plot_app?log=b815c6b1-707c-4a9b-bdf3-5bb7f41af758
CPU usage went to 100% shortly after arming due to the logger watchdog triggering.

Screenshot from 2020-04-05 13-04-37

### PR DESCRIPTION
**Pull request by bkueng**
When disconnecting USB poll returns successfully, but the read returns
-1 with ENOTCONN.
In addition this also ensures there's no busy loop when poll returns an
error.

MAVLink continues to work after reconnecting USB.

fixes  #14600

@MaEtUgR

### CODE REVIEW

File: src/modules/mavlink/mavlink_receiver.cpp [hunk 1]
```diff
@@ -2809,10 +2809,16 @@ MavlinkReceiver::Run()
...
-		if (poll(&fds[0], 1, timeout) > 0) {
+		int ret = poll(&fds[0], 1, timeout);
+
+		if (ret > 0) {
 			if (_mavlink->get_protocol() == Protocol::SERIAL) {
 				/* non-blocking read. read may return negative values */
 				nread = ::read(fds[0].fd, buf, sizeof(buf));
+
+				if (nread == -1 && errno == ENOTCONN) { // Not connected (can happen for USB)
+					usleep(100000);
```
Comment (MaEtUgR) [inline src/modules/mavlink/mavlink_receiver.cpp:2820]: Detail: time literal could be used

Comment (dagar) [reply src/modules/mavlink/mavlink_receiver.cpp:2820]: We should only use our time literals in the context of hrt. The base unit for hrt is currently microseconds, so coincidentally it currently fits in usleep, but it's possible it could change someday.

Comment (MaEtUgR) [reply src/modules/mavlink/mavlink_receiver.cpp:2820]: I see, always thought usleep and hrt and everything not float is microseconds in PX4 and hence we can use the literals. But that seems to be a naive assumption. 👍
