### PR TITLE
Tools: abort SITL start if gzserver fails

### LINKED ISSUE #15398: Sometimes SITL fails to start with "An instance of Gazebo is not running."
Every now and then when I start SITL Gazebo I see:
```
An instance of Gazebo is not running.
```

And afterwards it doesn't start up correctly.

This also lead to a timeout in MAVSDK CI:
https://github.com/mavlink/MAVSDK/pull/1149/checks?check_run_id=897897472

### PR DESCRIPTION
**Pull request by julianoes**
Sometimes gzserver seems to not start or not start fast enough. In this case, instead of stalling forever, it would be nice to abort.

Closes #15398.

### CODE REVIEW

File: Tools/sitl_run.sh [hunk 1]
```diff
@@ -105,8 +105,11 @@ elif [ "$program" == "gazebo" ] && [ ! -n "$no_sim" ]; then
 			fi
 		fi
 		SIM_PID=$!
-		gz model --spawn-file="${src_path}/Tools/sitl_gazebo/models/${model}/${model}.sdf" --model-name=${model} -x 1.01 -y 0.98 -z 0.83
 
+		if gz model --spawn-file="${src_path}/Tools/sitl_gazebo/models/${model}/${model}.sdf" --model-name=${model} -x 1.01 -y 0.98 -z 0.83 2>&1 | grep "An instance of Gazebo is not running."; then
```
Comment (dagar) [inline Tools/sitl_run.sh:109]: What's up with the magic coordinates? `-x 1.01 -y 0.98 -z 0.83`?

Comment (Jaeyoung-Lim) [reply Tools/sitl_run.sh:109]: @dagar That was something I added a while ago to spawn the vehicle somewhere that is not zero, and was specified in the world file previously.

Comment (hamishwillee) [reply Tools/sitl_run.sh:109]: @Jaeyoung-Lim Remember I asked the same question (see note below)? Perhaps worth an in-source comment.

image
