### PR TITLE
commander: fix battery failsafe without GPS

### LINKED ISSUE #13291: Battery failsafe does not cause DESCEND if local position not available
**Bug description**
Once the battery level reaches critical value the system tries to execute an RTL or LANDING, whichever is configured. The same process is repeated once the battery level reaches emergency level.
However, if no local position is available (altitude is available) then no failsafe will be executed, even if the battery is totally drained.
https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L343

**Alternative**
How about handling this case similar to when the vehicle loses RC signal and no local position is available (altitude is available)? In that case the system does a controlled descend.

**Screenshot from SITL testing on lastest master**
- allowed SITL to drain battery to 0
- enabled low battery failsafe (land)
- stopped gpssim such that only altitude but not xy position is valid

image

### PR DESCRIPTION
**Pull request by julianoes**
This fixes the battery failsafe for the following corner cases:
- Battery failsafe set to Return but we can't do RTL because we don't have a global position or home position. In this case we now switch to   Land. Land might end up in Descend in the failsafe state machine later.
- Battery failsafe set to Land but we can't land because we don't have a   local position. In this case we switch to land anyway and then fall back to descend in the failsafe state machine later.

The "fix" involves ignoring using the main_state_transition and implementing the guards in place. This is a hack for now but should cover the corner case until a more thorough refactor.

The different failsafe state machines have involved over time from requirements and learnings based on developed solutions and products. The implementations in various places will need to get consolidated in the future.

Tested in SITL for Return and Land with and without GPS.

Fixes #13291.

### CODE REVIEW

**Comment by julianoes** [comment]
@PX4/testflights please test this on the cheapest frame as follows:

For these tests I suggest to set the battery failsafe thresholds higher in QGC -> Settings -> Safety. (e.g. warning at 60%, failsafe at 50%, emergency at 20%. That way you don't need to risk damaging batteries.

Selection_062

**Test 1: Land with GPS**

1. Set the battery failsafe action to "Land" Mode.
2. Fly in POSCTL 2m above a possible landing spot.
3. Wait for the critical battery warning to appear. It should then nicely land.

 **Test 2: Land without GPS -> only when no wind!**

1. Set the battery failsafe action to "Land" Mode.
2. Disable GPS by doing `gps stop` in mavlink_shell.
3. Fly in ALTCL 2m above a possible landing spot (and some space for drift with wind).
4. Wait for the critical battery warning to appear. It should then descend (but drift with the wind).

**Test 3: RTL with GPS**

1. Set the battery failsafe action to "Return mode at critically low level,  Land mode at ..." Mode.
2. Fly in POSCTL maybe at 5m maybe about 10m from the takeoff position.
3. Wait for the critical battery warning to appear. It should then do RTL as usual. If the emergency battery level is also triggered it will switch to Land which would happen if the battery estimate goes down quickly.

**Test 4: RTL without GPS -> only when no wind!**

1. Set the battery failsafe action to "Return mode at critically low level,  Land mode at ..." Mode.
2. Disable GPS by doing `gps stop` in mavlink_shell.
3. Fly in ALTCL 2m above a possible landing spot (and some space for drift with wind).
4. Wait for the critical battery warning to appear. It should then descend (but drift with the wind).

Thanks and let me know if you have any questions!

**Comment by LorenzMeier** [comment]
@julianoes Thanks for providing a really good test plan. You're setting a very good example with that and a lot of PRs are lacking that.

File: src/modules/commander/state_machine_helper.cpp [hunk 1]
```diff
@@ -1145,25 +1145,23 @@ void battery_failsafe(orb_advert_t *mavlink_log_pub, const vehicle_status_s &sta
...
 		case LOW_BAT_ACTION::RETURN_OR_LAND:
 
-			// let us send the critical message even if already in RTL
-			if (TRANSITION_DENIED != main_state_transition(status, commander_state_s::MAIN_STATE_AUTO_RTL, status_flags,
-					internal_state)) {
-				mavlink_log_critical(mavlink_log_pub, "%s, Executing RTL", battery_critical);
+			if (status_flags.condition_global_position_valid && status_flags.condition_home_position_valid) {
+				internal_state->main_state = commander_state_s::MAIN_STATE_AUTO_RTL;
+				internal_state->timestamp = hrt_absolute_time();
+				mavlink_log_critical(mavlink_log_pub, "%s, executing RTL", battery_critical);
```
Comment (potaito) [inline src/modules/commander/state_machine_helper.cpp]: I saw that there are a few more `mavlink_log_` messages in state_machine_helper, that have this issue with the capitalization. Do you want to change all of them in a separate issue and leave it capitalized here, such that the various messages are at least congruently wrong? :smile:

File: src/modules/commander/state_machine_helper.cpp [hunk 2]
```diff
@@ -1145,25 +1145,23 @@ void battery_failsafe(orb_advert_t *mavlink_log_pub, const vehicle_status_s &sta
 		// FALLTHROUGH
 		case LOW_BAT_ACTION::RETURN_OR_LAND:
 
-			// let us send the critical message even if already in RTL
-			if (TRANSITION_DENIED != main_state_transition(status, commander_state_s::MAIN_STATE_AUTO_RTL, status_flags,
-					internal_state)) {
-				mavlink_log_critical(mavlink_log_pub, "%s, Executing RTL", battery_critical);
+			if (status_flags.condition_global_position_valid && status_flags.condition_home_position_valid) {
+				internal_state->main_state = commander_state_s::MAIN_STATE_AUTO_RTL;
```
Comment (potaito) [inline src/modules/commander/state_machine_helper.cpp]: Are we allowed to directly assign a new state by circumventing `main_state_transition()`? Perhaps because there would be no handling for the case where the state transition fails?

File: src/modules/commander/state_machine_helper.cpp (hunk 1 above)
Comment (julianoes) [reply src/modules/commander/state_machine_helper.cpp]: Thanks, yes let me decapitalize (is that a word?) the rest.

File: src/modules/commander/state_machine_helper.cpp (hunk 2 above)
Comment (julianoes) [reply src/modules/commander/state_machine_helper.cpp]: If you look inside `main_state_transition()` it's not doing anything else. So basically I only moved the boolean checks outside. I didn't know how else to fix this case without too much changes. It still needs proper refactoring.
If you have a nicer fix for this, I'm all ears.

Thanks for the review!

File: src/modules/commander/state_machine_helper.cpp (hunk 1 above)
Comment (potaito) [reply src/modules/commander/state_machine_helper.cpp]: Thanks :grin: 
_decapitalize_ can also mean to remove capital, but then again google image searches of PX4 show a gallery of handguns. So I don't think we have to worry about this :sweat_smile:

File: src/modules/commander/state_machine_helper.cpp (hunk 2 above)
Comment (potaito) [reply src/modules/commander/state_machine_helper.cpp]: No I don't. I was just wondering what your rationale is. I think it looks fine and makes the code actually less obscure.

**Comment by dannyfpv** [comment]
tested on pixhawk v4pro f-450

Test 1: Land with GPS
not disarm after land
https://review.px4.io/plot_app?log=4633646c-e55e-4c54-8c6f-a8df6c1502bf

Test 2: Land without GPS 
not disarm after land
https://review.px4.io/plot_app?log=056f0e27-9da1-4c55-8c99-196ad6f7620b

Test 3: RTL with GPS
Set the battery failsafe action to "Return mode at critically low level, Land mode at ..." Mode.
not disarm after land
https://review.px4.io/plot_app?log=399723f5-89dc-4a6b-8b3e-957c3d5117f3


Test 4: RTL without GPS 
Set the battery failsafe action to "Return mode at critically low level, Land mode at ..." Mode.
not disarm after land
https://review.px4.io/plot_app?log=0051d897-b88e-44ae-9c0c-376e6eacc30c

**Comment by julianoes** [comment]
@dannyfpv Thanks a lot for testing and the logs. I'm investigating the problem where it does not auto-disarm on landing. From the log I can see that landing is detected but then disarm does not happen. I can't reproduce this behaviour in SITL, so I'm wondering what might be different.

One thing that caught my eye is the weird noise/spikes in the mag values. It's something we need to investigate. I don't know if this has something to do with the fact that auto-disarm does not work.

**Comment by julianoes** [comment]
@dannyfpv @Tony3dr I'm trying to figure out if auto disarm did not work or if landing was not detected (and therefore auto disarm did not work). Do you remember?

From the logfiles, I'm not entirely sure. In some logfiles you switch to manual, in others you seem to use the kill switch.

**Comment by Tony3dr** [comment]
> @dannyfpv @Tony3dr I'm trying to figure out if auto disarm did not work or if landing was not detected (and therefore auto disarm did not work). Do you remember?
> 
> From the logfiles, I'm not entirely sure. In some logfiles you switch to manual, in others you seem to use the kill switch.

@julianoes the landing was detected, once the vehicle triggered the failsafe landing was detected. The reason why we switched to manual is to disarm the vehicle by using the kill switch. We can give it another go on Monday. Get more data to see if we can figure out what could be the issue.

File: src/modules/commander/state_machine_helper.cpp [hunk 3]
```diff
@@ -1194,13 +1195,9 @@ void battery_failsafe(orb_advert_t *mavlink_log_pub, const vehicle_status_s &sta
 
 		// FALLTHROUGH
 		case LOW_BAT_ACTION::LAND:
-			if (TRANSITION_DENIED != main_state_transition(status, commander_state_s::MAIN_STATE_AUTO_LAND, status_flags,
```
Comment (RomanBapst) [inline src/modules/commander/state_machine_helper.cpp]: @julianoes Sorry, I can't comment on a line which you did not change but don't you need to put the LOW_BAT_ACTION::RETURN_OR_LAND case before the LOW_BAT_ACTION::RETURN case, as you have done for the critical battery level section? As I understand it will otherwise fall through to landing and never RTL.

Comment (julianoes) [reply src/modules/commander/state_machine_helper.cpp]: I think this is correct because in the emergency case we want to land, so we fallthrough to land.

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5 f-450

Test 1: Land with GPS
Note:
Waited for the critical battery to appear the vehicle landed smoothly only issue is that the vehicle did not disarm after landing.
Log:
https://review.px4.io/plot_app?log=242b4d47-50f1-4975-9000-a5df63b92175

Test 2: Land without GPS
Note:
Waited for the critical battery warning to appear. The vehicle descends, drifted with the wind. Only issue is that the vehicle did not disarm after landing.
Log:
https://review.px4.io/plot_app?log=f34aeffd-50e4-48a3-a23d-69cadc351a12

Test 3: RTL with GPS
Notes:
Set the battery failsafe action to "Return mode at critically low level, Land mode at ..." Mode.
Waited for the critical battery warning to appear. The vehicle triggered RTL. The only issue noted is that the vehicle did not disarm after landing.
Logs:
https://review.px4.io/plot_app?log=c6e55aaa-f026-407a-bcad-29b7a73ee04c

Test 4: RTL without GPS
Notes:
Set the battery failsafe action to "Return mode at critically low level, Land mode at ..." Mode.
Waited for the critical battery warning to appear. The vehicle descends, drifted with the wind. The only issue noted is that the vehicle did not disarm after landing.
Logs:
https://review.px4.io/plot_app?log=e5602465-fc8e-4c44-a351-2a39ea96e114

@julianoes the test was completed, everything seemed to work as expected, except in all the tests the vehicle did not disarm upon touching the ground.

**Comment by julianoes** [comment]
@dannyfpv when you do a normal RTL with the same vehicle on master: does auto-disarm work?

**Comment by julianoes** [comment]
@dannyfpv I think your logs got a bit messed up above. The first two both seem to have GPS.

**Comment by julianoes** [comment]
@Tony3dr:
> @julianoes the landing was detected, once the vehicle triggered the failsafe landing was detected. 

Does that mean that the failsafe was done or that landing was actually detected and the props were spinning slower (but not disarmed)?

**Comment by julianoes** [comment]
From the logs I can tell that the problem seems to be the land estimator not triggering, rather than auto-disarm not working.

@bresch I'm looking at this log and I can't figure out why the land detector doesn't trigger:
https://review.px4.io/plot_app?log=f34aeffd-50e4-48a3-a23d-69cadc351a12

**Comment by Tony3dr** [comment]
> @dannyfpv I think your logs got a bit messed up above. The first two both seem to have GPS.
@julianoes sorry about that it looks like the order of the logs is off, see below. 
**Test 1: Land with GPS**
https://review.px4.io/plot_app?log=242b4d47-50f1-4975-9000-a5df63b92175
https://review.px4.io/plot_app?log=f34aeffd-50e4-48a3-a23d-69cadc351a12

**Test 2: Land without GPS**
https://review.px4.io/plot_app?log=c6e55aaa-f026-407a-bcad-29b7a73ee04c

**Test 3: RTL with GPS**
https://review.px4.io/plot_app?log=f34aeffd-50e4-48a3-a23d-69cadc351a12

**Comment by Tony3dr** [comment]
> @dannyfpv when you do a normal RTL with the same vehicle on master: does auto-disarm work?
@julianoes  we will post a couple of logs of the Master branch, later on, today we posted a couple in #13321, The landing problem is apparently an issue on current Master that is been worked on.

**Comment by dannyfpv** [comment]
tested on pixhawk4 v4 f-450
master firmware
mission mode: no issue
rtl: not disarm on land mode
log:
https://review.px4.io/plot_app?log=2f5469ab-ab04-4d7e-896e-11808f94a2df

**Comment by julianoes** [comment]
Ok, I'll merge this given the land detection issues are unrelated.
