### PR TITLE
Navigator resurrect FW GPS failure navigation

### LINKED ISSUE #7609: FW Land mode = crash
I recently had a flight that put up a "[commander] failsafe: no global position warning", then switched to Land mode and proceeded to fly straight into the earth. My main concern is why the global position was lost in the first place (did the estimated position and gps position begin to differ too much? why?), but it would be nice to know that there is a reliable FW solution for this sort of condition to return to the ground hopefully in one piece.

Log here: http://logs.px4.io/plot_app?log=b7fcb8a9-a66f-4b49-94e3-f896d3a65cb7

### PR DESCRIPTION
**Pull request by dagar**
GPS failure or loss of global position causes a transition to NAVIGATION_STATE_DESCEND, however this doesn't work for fixed wing as the position controller doesn't run without position updates.

 - fixes #7609

### CODE REVIEW

**Comment by dagar** [comment]
Not currently working due to navigator only running with global position updates.

**Comment by Antiheavy** [comment]
random thought:  Manual and Stabilize mode work without global position; does Altitude mode work without global position?  If it does, then does it use airspeed and baro somehow?

**Comment by dagar** [comment]
Altitude control mode does not work without global position, although it should. That's the architectural reason we're limited to this for now.

**Comment by AndreasAntener** [comment]
@dagar I've proposed that before: having only one position topic (a merge of the two) would make things much easier. Not sure anymore though what the outcome of that discussion was ;)

**Comment by dagar** [comment]
@AndreasAntener ah yes I remember. I must admit at the time I thought it was a bad idea, but now I see the benefit of using local position everywhere. I don't think we need to merge them though. I did an initial pass converting fw_pos_control to local_position not too long ago, but there's a lot of detail to verify.

Even with that in place we'd still need special handling for navigation, and I'm not sure at what point we should stop trusting local_pos.z.

**Comment by mhkabir** [comment]
+1 for using local position in the fixedwing controllers

**Comment by AndreasAntener** [comment]
@dagar ah yes, that PR. Merging both would only be an intermediate step if the goal is to use local coordinates everywhere. Using only one position topic but providing both global and local coordinates already simplifies things a lot though.

File: src/modules/navigator/gpsfailure.h [hunk 1]
```diff
@@ -58,14 +55,11 @@ class GpsFailure : public MissionBlock
 {
 public:
 	GpsFailure(Navigator *navigator, const char *name);
+	~GpsFailure() = default;;
```
Comment (julianoes) [inline src/modules/navigator/gpsfailure.h]: Too many semicolons 😄

File: src/modules/navigator/gpsfailure_params.c [hunk 2]
```diff
@@ -56,12 +51,12 @@
  * @increment 1
  * @group GPS Failure Navigation
  */
-PARAM_DEFINE_FLOAT(NAV_GPSF_LT, 30.0f);
+PARAM_DEFINE_FLOAT(NAV_GPSF_LT, 0.0f);
```
Comment (julianoes) [inline src/modules/navigator/gpsfailure_params.c]: This is a drastic change. Wouldn't it be a sane default to have some loiter time before going into termination?

Comment (dagar) [reply src/modules/navigator/gpsfailure_params.c]: Actually my intent is the opposite, by default continue loitering with no throttle all the way to the ground. If someone wants terminate they'd have to enable it.

Comment (julianoes) [reply src/modules/navigator/gpsfailure_params.c]: Oh, got it!

**Comment by dagar** [comment]
Given we're headed in this direction I think an acceptable fix here is to have navigator run with local position updates.

**Comment by dagar** [comment]
Tested in simulation by killing the GPS driver. https://logs.px4.io/plot_app?log=4c106235-cc59-49aa-88d9-d29337fcc854 (see ground truth once gps stops)

**Comment by Antiheavy** [comment]
neat.  is it possible to restart the GPS driver to simulate regaining GPS?  Does it switches out of fail-safe and back to it's previous guidance mode upon GPS regain?

**Comment by dagar** [comment]
It will resume the previous AUTO mode (mission, hold, rtl, etc).

Here's another SITL mission test where I killed the GPS driver and restarted it ~15s later.
https://logs.px4.io/plot_app?log=64ce41d2-adba-490b-9359-4c66e56eecc6

**Comment by dagar** [comment]
@ChristophTobler @Stifael as this now makes navigator run on local position updates (but otherwise doesn't change it) could one of you also review?

I'd like to get this in soon as as possible, it's quite important for surviving both GPS and EKF issues.

File: src/modules/commander/state_machine_helper.cpp [hunk 3]
```diff
@@ -669,20 +670,21 @@ bool set_nav_state(struct vehicle_status_s *status,
...
-			enable_failsafe(status, old_failsafe, mavlink_log_pub, reason_no_gps_cmd);
-
 		} else if (status_flags->rc_signal_lost_cmd) {
 			status->nav_state = vehicle_status_s::NAVIGATION_STATE_AUTO_RCRECOVER;
 
 		} else if (status_flags->vtol_transition_failure_cmd) {
 			status->nav_state = vehicle_status_s::NAVIGATION_STATE_AUTO_RTL;
 
-			/* finished handling commands which have priority, now handle failures */
+		} else if (status_flags->gps_failure || status_flags->gps_failure_cmd) {
```
Comment (Stifael) [inline src/modules/commander/state_machine_helper.cpp]: what does the gps_failure_cmd exist and when is this set to true? 
I did not understand it from the flag description

File: src/modules/navigator/gpsfailure.cpp [hunk 4]
```diff
@@ -96,25 +90,36 @@ GpsFailure::on_activation()
...
-			hrt_abstime elapsed = hrt_elapsed_time(&_timestamp_activation);
-
-			//warnx("open loop loiter, posctl enabled %u, elapsed %.1fs, thrust %.2f",
-			//_navigator->get_control_mode()->flag_control_position_enabled, elapsed * 1e-6, (double)_param_openlooploiter_thrust.get());
-			if (elapsed > _param_loitertime.get() * 1e6f) {
-				/* no recovery, adavance the state machine */
-				warnx("gps not recovered, switch to next state");
-				advance_gpsf();
+			if (_param_loitertime.get() > FLT_EPSILON) {
+				if (hrt_elapsed_time(&_timestamp_activation) > _param_loitertime.get() * 1e6f) {
```
Comment (Stifael) [inline src/modules/navigator/gpsfailure.cpp]: this is basically a `&&` condition

File: src/modules/navigator/navigator_main.cpp [hunk 5]
```diff
@@ -57,20 +57,16 @@
...
-#include <arch/board/board.h>
-
-#include <uORB/uORB.h>
 #include <uORB/topics/fw_pos_ctrl_status.h>
 #include <uORB/topics/home_position.h>
 #include <uORB/topics/mission.h>
 #include <uORB/topics/vehicle_command.h>
 #include <uORB/topics/vehicle_status.h>
 #include <uORB/uORB.h>
+#include <uORB/uORB.h>
```
Comment (Stifael) [inline src/modules/navigator/navigator_main.cpp]: 2x included

File: src/modules/navigator/navigator_main.cpp [hunk 6]
```diff
@@ -267,25 +263,18 @@ Navigator::task_main()
 	px4_pollfd_struct_t fds[1] = {};
 
 	/* Setup of loop */
-	fds[0].fd = _global_pos_sub;
+	fds[0].fd = _local_pos_sub;
 	fds[0].events = POLLIN;
 
-	bool global_pos_available_once = false;
-
 	/* rate-limit global pos subscription to 20 Hz / 50 ms */
```
Comment (Stifael) [inline src/modules/navigator/navigator_main.cpp]: wrong description. would now be local

File: src/modules/navigator/navigator_main.cpp [hunk 7]
```diff
@@ -324,10 +306,14 @@ Navigator::task_main()
 		}
 
 		/* local position updated */
```
Comment (Stifael) [inline src/modules/navigator/navigator_main.cpp]: wrong description

File: src/modules/commander/state_machine_helper.cpp (hunk 3 above)
Comment (dagar) [reply src/modules/commander/state_machine_helper.cpp]: For testing presumably, but they aren't used by any test code we have. I left it in tact because I'm getting rid of all the cmds in the commander refactor https://github.com/PX4/Firmware/pull/7517.
For testing I'll use the actual gps_failure status flag instead.

File: src/modules/navigator/gpsfailure.cpp (hunk 4 above)
Comment (dagar) [reply src/modules/navigator/gpsfailure.cpp]: fixed

File: src/modules/navigator/navigator_main.cpp (hunk 5 above)
Comment (dagar) [reply src/modules/navigator/navigator_main.cpp]: fixed

File: src/modules/navigator/navigator_main.cpp (hunk 6 above)
Comment (dagar) [reply src/modules/navigator/navigator_main.cpp]: fixed

File: src/modules/navigator/navigator_main.cpp (hunk 7 above)
Comment (dagar) [reply src/modules/navigator/navigator_main.cpp]: fixed
