### PR TITLE
AUX fix, better boot messaging

### LINKED ISSUE #2644: AUX ports currently broken
@LorenzMeier just in case you missed my not so obvious comment on the PR, this change da4d8a5c2b9ff220877caa976671a46a887bdd78 breaks AUX port usage.

Checking for the existence of ```/dev/pwm_output1``` looks like it will always fail since ```/dev/pwm_output1``` doesn't exist until ```fmu mode_pwm``` is executed.

Perhaps this check can be done further down before the mixer loads or just do with using the ```SYS_USE_IO``` parameter?

### PR DESCRIPTION
**Pull request by LorenzMeier**
@sjwilks This should fix #2644.

### CODE REVIEW

File: ROMFS/px4fmu_common/init.d/rc.interface [hunk 1]
```diff
@@ -128,16 +121,24 @@ then
 	then
 		if fmu mode_pwm
 		then
-			if mixer load $OUTPUT_AUX_DEV $MIXER_AUX_FILE
+			if [ -f $OUTPUT_AUX_DEV ]
```
Comment (SimonWilks) [inline ROMFS/px4fmu_common/init.d/rc.interface]: If you use the -e operator instead of -f it works (-f checks for regular files only).

Comment (LorenzMeier) [inline ROMFS/px4fmu_common/init.d/rc.interface]: When you invest the effort to test, could you just push a commit onto the branch? Its not that I "own" the pull request and its much better to have what you tested in a commit, rather than me interpreting what you mean verbally and doing an open loop change (or needing to wait for another test (which is tedious for you as well) from your side.
