### PR TITLE
FlightTasks: add Descend task to land without GPS

### LINKED ISSUE #11468: Land failsafe broken without GPS
When flying without GPS and losing RC the vehicle goes into land mode (given that it has been configured that way).
But the vehicle never detects landing because something with the flight task is broken (see messages below).

┆Attachments: <a href="https://storage.www.wrike.com/attachments/84900317?accountId=2022386">Image-2019-02-16 01-08-33.png</a>

### PR DESCRIPTION
**Pull request by julianoes**
This adds a flight task to catch the case where we want to do an emergency descent without GPS but only a baro.

Previously, this would lead to the navigator land class being called without position estimates which then made the flight tasks fail and react with a flight task failsafe. This however meant that landed was never detected and a couple of confusing error messages.

This applies if NAV_RCL_ACT is set to 3 "land".

Fixes #11468.

Tested in SITL with `iris`, `plane`, and `standard_vtol`.

### CODE REVIEW

**Comment by julianoes** [comment]
I tried this with and without GPS with`vtol_standard` and in both cases it transitioned to multicopter flight and then descended. I think that's correct but I don't exactly understand why/how the backtransition is triggered.

**Comment by ThomasRigi** [comment]
> I tried this with and without GPS with`vtol_standard` and in both cases it transitioned to multicopter flight and then descended. I think that's correct but I don't exactly understand why/how the backtransition is triggered.

@julianoes I think this is due to NAV_FORCE_VT parameter. Not sure about the exact implementation though. If NAV_FORCE_VT is true then the vehicle will / should always land (and takeoff) in MC mode. Meaning that if you deactivate it it should stay in FW for landing

**Comment by bresch** [comment]
I also don't really see the advantage over the failsafe flight task. Also, no GPS doesn't mean no position/velocity estimate, the drone can still have an optical flow sensor and brake horizontal speed.

**Comment by julianoes** [comment]
The failsafe task will actually stay at the same position because we have a valid z-position, however, we should descend.

**Comment by julianoes** [comment]
@MaEtUgR please review.

**Comment by julianoes** [comment]
@Tony3dr I would appreciate if you could test this pull request carefully on the cheapest multicopter :smile::

**Test instructions**
Before the tests:
1. Set RC failsafe to Land (NAV_RCL_ACT = 3)
2. Make sure RC failsafe is correctly detected (on ground)

1. Test:
Hover in POSCTL, then switch off RC -> it should land nicely

2. Test:
Fly without GPS, so after powering on PX4, open mavlink shell and do `gps stop`.
Hover in ALTCTL (maybe around 1-2 meters), then switch off RC -> it should descend/land but it will drift with wind, so you need to make sure you have enough space and no wind!

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+ */
+
+#include "FlightTaskDescend.hpp"
+
+bool FlightTaskDescend::activate(vehicle_local_position_setpoint_s last_setpoint)
+{
+	bool ret = FlightTask::activate(last_setpoint);
+	_position_setpoint = {NAN, NAN, NAN};
+	_velocity_setpoint = {NAN, NAN, NAN};
+	_thrust_setpoint = matrix::Vector3f(0.0f, 0.0f, -_param_mpc_thr_hover.get() * 0.6f);
```
Comment (MaEtUgR) [inline src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Not to myself: This conflicts with #12072 and will only show up as a compile error.

File: src/modules/navigator/navigator_main.cpp [hunk 2]
```diff
@@ -620,6 +615,7 @@ Navigator::run()
 		case vehicle_status_s::NAVIGATION_STATE_ACRO:
 		case vehicle_status_s::NAVIGATION_STATE_ALTCTL:
 		case vehicle_status_s::NAVIGATION_STATE_POSCTL:
+		case vehicle_status_s::NAVIGATION_STATE_DESCEND:
```
Comment (MaEtUgR) [inline src/modules/navigator/navigator_main.cpp]: It would anyways run into default.

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+/**
+ * @file FlightTaskDescend.cpp
+ */
+
+#include "FlightTaskDescend.hpp"
+
+bool FlightTaskDescend::activate(vehicle_local_position_setpoint_s last_setpoint)
+{
+	bool ret = FlightTask::activate(last_setpoint);
+	_position_setpoint = {NAN, NAN, NAN};
```
Comment (MaEtUgR) [inline src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: There's also `_position_setpoint.setNAN();` but you don't need to set anything NAN that your task didn't touch. By definition all setpoints are NAN on activation and will stay whatever you set them to. E.g. you also don't need to set the jerk and yawspeed.
```suggestion
```

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+	_velocity_setpoint = {NAN, NAN, NAN};
+	_thrust_setpoint = matrix::Vector3f(0.0f, 0.0f, -_param_mpc_thr_hover.get() * 0.6f);
+	_yaw_setpoint = _yaw;
+	_yawspeed_setpoint = 0.0f;
```
Comment (MaEtUgR) [inline src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]:
```suggestion
```

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+ * @file FlightTaskDescend.cpp
+ */
+
+#include "FlightTaskDescend.hpp"
+
+bool FlightTaskDescend::activate(vehicle_local_position_setpoint_s last_setpoint)
+{
+	bool ret = FlightTask::activate(last_setpoint);
+	_position_setpoint = {NAN, NAN, NAN};
+	_velocity_setpoint = {NAN, NAN, NAN};
```
Comment (MaEtUgR) [inline src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]:
```suggestion
```

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+	_yaw_setpoint = _yaw;
+	_yawspeed_setpoint = 0.0f;
+	return ret;
+}
+
+bool FlightTaskDescend::update()
+{
+	if (PX4_ISFINITE(_velocity(2))) {
+		// land with landspeed
+		_velocity_setpoint(2) = _param_mpc_land_speed.get();
```
Comment (MaEtUgR) [inline src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Currently (before #12072) setting a thrust in z direction cannot be combined with a velocity. With acceleration setpoint this would work but it's probably not what you want here anyways.

**Comment by julianoes** [comment]
@Tony3dr sorry, don't test just yet. We need to change something first.

**Comment by Tony3dr** [comment]
> @Tony3dr sorry, don't test just yet. We need to change something first.
Sounds good let us know when it's ready.

**Comment by MaEtUgR** [comment]
@julianoes I pushed on your pr, I hope that's ok.

- The first commit I squeezed in is fixing the failsafe handling if erroneous non-executable setpoints get into the position controller which was the case before. It then still does an emergency descend but spitting warnings this time.
- The second commit is yours unchanged
- The third commit contains my suggestions to use the flight task interface for that case.

I tested before and after the descend introduction and it does the right thing in the case you described (default configuration `NAV_RCL_ACT = 3` suffered the same problem). The case where you lose the altitude estimate is hard to test currently... not sure if that's supported at the moment.

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp (hunk 6 above)
Comment (julianoes) [reply src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Ok, nice.

**Comment by julianoes** [comment]
@MaEtUgR I've tested these cases:

1. NAV_RCL_ACT=3 -> GPS ok and RC lost -> switches from POSCTL to LAND and lands :heavy_check_mark: 
2. NAV_RCL_ACT=3 -> no GPS and RC lost -> switches from POSCTL to LAND and descends :heavy_check_mark: 
3. NAV_RCL_ACT=0 -> GPS ok and RC lost -> stays still in POSCTL and stays still :heavy_check_mark: 
4. NAV_RCL_ACT=0 -> no GPS and RC lost -> stays in ALTCTL but descends :heavy_multiplication_x:

For 4. the output is:
```
WARN  [commander] Manual control lost
WARN  [mc_pos_control] Position-Control Setpoint-Update failed
WARN  [mc_pos_control] Failsafe: blind hover
```

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp (hunk 3 above)
Comment (MaEtUgR) [reply src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Fixed in https://github.com/PX4/Firmware/pull/13143/commits/e67b5dbc94a03e45e152a853a266c7c79239c221

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp (hunk 4 above)
Comment (MaEtUgR) [reply src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Fixed in https://github.com/PX4/Firmware/pull/13143/commits/e67b5dbc94a03e45e152a853a266c7c79239c221

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp (hunk 5 above)
Comment (MaEtUgR) [reply src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Fixed in https://github.com/PX4/Firmware/pull/13143/commits/e67b5dbc94a03e45e152a853a266c7c79239c221

File: src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp (hunk 6 above)
Comment (MaEtUgR) [reply src/lib/FlightTasks/tasks/Descend/FlightTaskDescend.cpp]: Fixed in https://github.com/PX4/Firmware/pull/13143/commits/e67b5dbc94a03e45e152a853a266c7c79239c221

**Comment by MaEtUgR** [comment]
@julianoes 
1. "stays in ALTCTL but descends" that's what I implemented because:
   - you are in altitude mode relying on RC
   - you loose RC but have no reaction so you stay relying on it
   - the consumer trying to use RC is failing so you go into last resort handling
   - there's no GPS to just stop and wait so it stays level and will start drifting
   - **because drifting without RC is not a sustainable state it's descending**
   I consider this much safer than any other solution like staying on altitude drifting away which is a flyaway or terminating which is probably unexpected and is likely causing more damage.
2. You must be running a different/old branch since I replaced the posted message
   > Failsafe: blind hover

Can you check again?

**Comment by julianoes** [comment]
@MaEtUgR I checked 4. again and you're right. It's now correct. And I agree with your reasoning of switching to descend for this case.

**Comment by julianoes** [comment]
So now the only thing is to figure out how this fits into fmu-v2.

**Comment by julianoes** [comment]
@Tony3dr ok I think you can go ahead and test this now:


**Test instructions**
Before the tests:
1. Set RC failsafe to Land (NAV_RCL_ACT = 3)
2. Make sure RC failsafe is correctly detected (on ground)

1. Test:
Hover in POSCTL, then switch off RC -> it should land nicely

2. Test:
Fly without GPS, so after powering on PX4, open mavlink shell and do `gps stop`. Don't disconnect the GPS, otherwise you don't have the external mag.
Hover in ALTCTL (maybe around 1-2 meters), then switch off RC -> it should descend/land but it will drift with wind, so you need to make sure you have enough space and no wind!

**Comment by dannyfpv** [comment]
tested on pixhawk4 v5 f-450

NAV_RCL_ACT = land mode

1 log switch off RC with GPS: no issues
https://review.px4.io/plot_app?log=2ea6423f-b232-45c9-8c40-32e775118359

2 log switch off RC without GPS: no issues  drift with wind 30 meters
https://review.px4.io/plot_app?log=3104d449-dd29-473f-9055-354984ff8afa

**Comment by LorenzMeier** [comment]
I've updated the branch - let's see if it passes now.

**Comment by julianoes** [comment]
@dannyfpv thanks a lot for testing and adding the logs, that's very helpful!

@MaEtUgR we need to check the descend case, something is odd with throttle:

bokeh_plot

**Comment by julianoes** [comment]
@MaEtUgR it looks like ground_contact triggers but always after throttle is set to 0, somehow.

ground_contact

**Comment by julianoes** [comment]
Looking at the vertical position z estimate it looks like not enough vertical movement which triggered the ground contact.

no-vertical-movement

**Comment by julianoes** [comment]
@bresch and I found that the land detector determined:

1. `vertical_movement` to be `false`: https://github.com/PX4/Firmware/blob/95dc522b99688a08402ac6462ad28f5dfd338eda/src/modules/land_detector/MulticopterLandDetector.cpp#L154
2. `hit_ground` to be `true`: https://github.com/PX4/Firmware/blob/95dc522b99688a08402ac6462ad28f5dfd338eda/src/modules/land_detector/MulticopterLandDetector.cpp#L165

This happens because the z controller only reacts slowly to the new setpoint so the z velocity down is much less than the z velocity setpoint here:
https://github.com/PX4/Firmware/blob/95dc522b99688a08402ac6462ad28f5dfd338eda/src/modules/land_detector/MulticopterLandDetector.cpp#L151-L154

It looks to us that we should check the land detector for this edge cases in a future pull request. The issue is general and not specific to this change. Therefore we can merge this PR already.
