### PR TITLE
Navigator: Fix RTL backtransition for VTOL. Fixes #7405

### LINKED ISSUE #7405: 1.6.2 VTOL RTL does not trigger back-transition
I think that this commit breaks the back-transition when RTL is commanded to a VTOL drone:
https://github.com/PX4/Firmware/pull/7249

However I'm not 100% sure since my drone doesn't work with master or stable. @dagar suggested that this could easily be tested in SITL, although I don't have that setup at the moment. I would appreciate it if someone can verify this with SITL.

### PR DESCRIPTION
**Pull request by LorenzMeier**
A recent change removed the command forwarding required for VTOL transitions. This change brings this back.

Partially reverts https://github.com/PX4/Firmware/pull/7249

### CODE REVIEW

File: src/modules/navigator/rtl.cpp [hunk 1]
```diff
@@ -300,6 +300,11 @@ RTL::set_rtl_item()
 
 	reset_mission_item_reached();
 
+	/* execute command if set. This is required for commands like VTOL transition */
+	if (!item_contains_position(&_mission_item)) {
+		issue_command(&_mission_item);
```
Comment (dagar) [inline src/modules/navigator/rtl.cpp]: issued_command() includes checking item_contains_position().

Comment (LorenzMeier) [inline src/modules/navigator/rtl.cpp]: I will keep it for now since it's more readable. Let's hope the compiler is smart..
