### PR TITLE
AutoSmoothVel - Compute desired speed at target based on path curvature

### LINKED ISSUE #11827: Trajectory mission slow final waypoint approach
**Describe the bug**
When using the Jerk-limited trajectory (default, `MPC_AUTO_MODE` 1) the final approach to a waypoint for example but not limited to the return altitude in RTL is significantly slower than with the previous implementation. Don't get me wrong, I would not prefer the old implementation but I think it's something we need to fix with medium priority.

**To Reproduce**
It's also visible in SITL:
1. Fly e.g. 10m away from home
2. Trigger RTL while you're clearly lower than the return altitude
3. Pay attention to the vehicle reaching the return altitude
4. It it's a very continuous motion but it almost looks like it's breaking too early and then takes quite long to fly into the acceptance radius and continue. The same can be observed in other missions.

**Expected behavior**
It's clear that a jerky corner takes less time and we don't have an optimized trajectory around corners yet but it would be nice if the vehicle could break down what intuitively looks more spot on to the waypoint. Maybe that's just tuning.

**Log Files and Screenshots**
Should I create a comparison for approaching times?

**Drone:**
- First seen in SITL and default parameters
- Now tested in real world on a small racing platform

**Additional context**
Original trajectory based mission pr: https://github.com/PX4/Firmware/pull/10746

### PR DESCRIPTION
**Pull request by bresch**
**Describe problem solved by the proposed pull request**
Currently, the drone does waypoint navigation while almost stopping at each waypoint. When the waypoints are aligned or that the heading change is small, we should not completely stop the drone but rather decelerate to make a nice turn and continue. 

**Describe your preferred solution**
The solution implemented in that PR assumes that the drone will fly an arc between the two lines connecting to a waypoint and that we want to fly this arc with some desired centripetal acceleration. Given the acceptance radius `r`, the desired centripetal acceleration `ac` and the angle between the two lines α, we can easily compute the desired waypoint speed:
<a href="https://www.codecogs.com/eqnedit.php?latex=\\&space;a_c=\frac{v^2}{R}&space;\\&space;R&space;=&space;r\tan(\alpha/2)&space;\\&space;v_{in}&space;=&space;\sqrt{a_cr\tan(\alpha/2)}" target="_blank"></a>

waypoint_circle

Also, to avoid entering too fast into the waypoint if the next waypoint is really close, the maximum speed between current and next is computed to constrain the waypoint speed.

You can interactively estimate the waypoint speed by clicking on the following link:
https://www.desmos.com/calculator/rvx6uybeo8

**Tests**
I tested quite extensively in SITL and on a F550.
Here an example of a log:
https://logs.px4.io/plot_app?log=2ab24653-a229-4e81-8295-ee7c58c8a373

**Related**
Fixes #11827

### CODE REVIEW

**Comment by bresch** [comment]
@PX4/testflights Can you test this PR in mission (survey and random mission) please? The drone should slow down but not stop if the turn is not too sharp.

File: src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp [hunk 1]
```diff
@@ -177,6 +177,50 @@ void FlightTaskAutoLineSmoothVel::_checkEkfResetCounters()
 	}
 }
 
+float FlightTaskAutoLineSmoothVel::_getSpeedAtTarget()
```
Comment (Stifael) [inline src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp]: can we move the two new methods into a UtilityClass/Function with more general names? then we can reuse it in other tasks as well

**Comment by Stifael** [comment]
looks great. will try to test it tomorrow on H520

**Comment by hamishwillee** [comment]
What if the angle is really acute?

**Comment by bresch** [comment]
@hamishwillee The circle with radius R gets smaller and when the angle is 0, the radius is 0 and the desired entrance speed is 0.

**Comment by Stifael** [comment]
I tested it on the H520 and seems to work well. I think it is a bit too conservative at corners and approaches the waypoints a bit too slow. Can that be changed via tuning?

During one particular survey, the vehicle also experienced an abrupt stop at one of the waypoints (see below), where the drone first accelerated before it stopped abruptly.
6_7_survey_point. 

The flight log:
https://review.px4.io/plot_app?log=18956ebf-a86d-4c72-a786-1f97ca318130

In addition, to prevent the vehicle from passing a waypoint if the altitude has not been reached yet, I created this [PR](https://github.com/PX4/Firmware/pull/12511).

**Comment by jorge789** [comment]
### Tested on PixRacer V4:

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
The flight was good the vehicle followed the points marked in the mission only slowing down but without stopping.No issues were noted, good flight in general.

**Logs:**
https://review.px4.io/plot_app?log=d1f4a5f9-5c98-4ea2-9e48-12555472fbb4

https://review.px4.io/plot_app?log=8e5b032a-ec31-48e4-9ec6-9ae59b0ded49

https://review.px4.io/plot_app?log=293a137f-56b3-47d0-9a00-46760d04b4e2

**Comment by Junkim3DR** [comment]
### Tested on Pixhawk 4 mini v5:

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
Vehicle flew as expected, slowed down instead of stoping at the waypoints.

**Logs:**
- https://review.px4.io/plot_app?log=940fe94e-7748-465d-8452-83dff04ff446
- https://review.px4.io/plot_app?log=33867777-e6e7-4492-bc92-34a6787c0b82

### Tested on Pixhawk Pro v4:

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
Vehicle flew as expected, slowed down instead of stoping at the waypoints.

**Logs:**
- https://review.px4.io/plot_app?log=da846d10-3b89-4ea5-9100-a0945e82a45d
- https://review.px4.io/plot_app?log=d7e2892f-6af2-4488-a9a4-2159cc19ee92


### Tested on NXP FMUK66 v3:

**Flight Card 2**

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Take off in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
Vehicle flew as expected, slowed down instead of stoping at the waypoints.

**Logs:**
- https://review.px4.io/plot_app?log=520ad010-985c-4576-b88f-9c7026c95525
- https://review.px4.io/plot_app?log=d87d6228-6510-4f2f-95c4-a2453a82c4b9

File: src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp (hunk 1 above)
Comment (jkflying) [reply src/lib/FlightTasks/tasks/AutoLineSmoothVel/FlightTaskAutoLineSmoothVel.cpp]: Agreed, it would be great to use the `_getMaxSpeedFromDistance` in the collision prevention as well, instead of using just the velocity controller P gain.

**Comment by bresch** [comment]
@Stifael I moved the computation in static functions inside the VelocitySmoothing class that contains the jerk-limited optimizer. Is that enough or do you want them in an other file (header library? what would be the scope of the library? name? ...)

**Comment by Stifael** [comment]
>  Is that enough or do you want them in an other file (header library? what would be the scope of the library? name? ...)

Do you think it makes sense to have `computeMaxSpeedFromBrakingDistance`  and the other function in `VelocitySmoothing`? 

I think if the function has a general implementation and is not necessarily FlightTasks related, then it could be put into the math-library similar to other functions (https://github.com/PX4/Firmware/blob/master/src/lib/mathlib/math/Functions.hpp#L48-L208). If it will anyway just be used by FlightTasks, then I would put it in a file such that it can easily be found. For instance, `computeMaxSpeedFromBrakingDistance` is kind of smooth-independent and can also be used in FlightTaskAutoLine.
However, I don't want to block you, so sure we can do that in another PR, given that I anyway want to revisit the structure.

**Comment by bresch** [comment]
@Stifael I moved the functions into a `TrajMath.hpp` header library. It's true it's much cleaner and reusable. Can you review again?

File: src/lib/FlightTasks/tasks/Utility/TrajMath.hpp [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+ * Equation to solve: 0 = vel^2 - 2*accel*(x - vel*2*accel/jerk)
+ *
+ * @param jerk maximum jerk
+ * @param accel maximum acceleration
+ * @param braking_distance distance to the desired stopping point
+ *
+ * @return maximum speed
+ */
+template<typename T>
+const T computeMaxSpeedFromBrakingDistance(T jerk, T accel, T braking_distance)
```
Comment (jkflying) [inline src/lib/FlightTasks/tasks/Utility/TrajMath.hpp]: Awesome! I'll try to get this into the collision prevention as well.

**Comment by bresch** [comment]
@PX4/testflights Can you test that again please?

**Comment by dannyfpv** [comment]
Tested on Pixhawk4 v5 f-450

Modes Tested
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

Procedure
Arm and Takeoff in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

Pr log:
https://review.px4.io/plot_app?log=421760b0-a1cb-4e00-836d-ca085d17b475

https://review.px4.io/plot_app?log=d3b10670-b737-4657-9ea8-9484d79ecbdf

**Comment by bresch** [comment]
@dannyfpv Thanks a lot! Ready to be merged once we have a bit more space on the omnibus target :|

**Comment by Junkim3DR** [comment]
### Tested on PixRacer v4:

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Takeoff in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
No issue noted, good flight in general.

**Logs:**
- https://review.px4.io/plot_app?log=ce61c4f8-4c1c-4814-9c96-7e529176721e
- https://review.px4.io/plot_app?log=1d16a5c9-ab2c-42b2-9c68-daa7819d7138


### Tested on Pixhawk Pro v4Pro:

**Modes Tested**
Mission Plan Mode (Automated): Good.
RTL (Return To Land): Good.

**Procedure**
Arm and Takeoff in mission plan mode then make sure that vehicle follows all waypoints as shown in QGC, once completed all waypoint see landing behavior.

**Note:**
No issue noted, good flight in general.

**Logs:**
- https://review.px4.io/plot_app?log=b16b62fc-14d7-4e6c-b992-22d1df2f2b77
- https://review.px4.io/plot_app?log=0c071055-d7dd-499c-ae10-6e9f3ba7871e
