### PR TITLE
px4io: When running HITL, don't publish actuator_outputs. Fixes #13471.

### LINKED ISSUE #13471: v1.10.0-rc quadcopter doesn't take off in HITL/jMAVsim
**Describe the bug**
Set up HITL simulation with jMAVsim on Ubuntu 18.04,  Pixhawk 4 with v1.10.0-rc, locally built px4_fmu-v5-multicopter. 

**To Reproduce**
1. Follow the recipe from [px4 website](https://dev.px4.io/v1.9.0/en/simulation/hitl.html#jmavsimgazebo-hitl-environment)
2. Using Manual/Stabilized mode, arm vehicle and apply throttle
3. Vehicle does not take off
4. Mavlink shell (`listener` command) shows actuator_outputs_1 with *valid* values and actuator_outputs_0 with 0 values

**Expected behavior**
SERVO_OUTPUT_RAW or HIL_ACTUATOR_CONTROLS should follow actuator_outputs_1 and the vehicle should take off in simulation

**Log Files and Screenshots**
[Flight Review Link](https://review.px4.io/plot_app?log=8890b998-3b24-4a96-af5a-da4c10910bff)

Add screenshots to help explain your problem.

**Drone:**
- Pixhawk4 running in HITL Quad Mode
- Photo of the IMU / autopilot setup if possible.
IMG_8020

### PR DESCRIPTION
**Pull request by langrind**
See [Issue 13471 - vehicle doesn't take off in HITL SIM](https://github.com/PX4/Firmware/issues/13471)

The reason it fails:

When running in HITL mode, pwm_out_sim publishes actuator_outputs.

px4io unconditionally publishes the uOrb actuator_outputs. When HITL
is configured, the px4io copy of the uOrb has all zeros.

The result is that there are two publications, one valid, and one
all-zeros. This causes the HIL_ACTUATOR_CONTROLS mavlink message
to be incorrect (all-zeros) and the SERVO_OUTPUTS_RAW mavlink
message to be inconsistent, as it takes the data from one or the
other uOrb randomly each cycle.

The fix is to let px4io know that HITL is in effect when it is
started, and modify px4io to suppress publication in this case.

This is a bigger more complicated fix than I would like, but I
think it is conceptually correct.

An alternative would be to change src/modules/mavlink/mavlink_messages.cpp so that
MavlinkStreamHILActuatorControls() explicitly subscribed to instance 1 of the uOrb:

         _act_sub(_mavlink->add_orb_subscription(ORB_ID(actuator_outputs), 1)), _act_time(0)

That's a one-line solution, but I think it is incorrect because nothing enforces which pub of the uOrb is instance 0 and which is instance 1. And, I just think it doesn't make sense to have two pubs.

**Test data / coverage**
I simply verified that the failure case in #13471 is fixed. I also verified that the Pixhawk still boots when HITL is not enabled.

Signed-off-by: Nik Langrind <langrind@gmail.com>

### CODE REVIEW

**Comment by dagar** [comment]
Thanks, this is something that's been broken multiple times.

**Comment by LorenzMeier** [comment]
@julianoes @dagar Do we want to pull this into 1.10? I'm tending towards it.

File: src/drivers/px4io/px4io.cpp [hunk 1]
```diff
@@ -2992,19 +3004,22 @@ start(int argc, char *argv[])
...
-	/* disable RC handling on request */
-	if (argc > 1) {
-		if (!strcmp(argv[1], "norc")) {
-
+	/* disable RC handling and/or actuator_output publication on request */
+	for (int extra_args = 1; extra_args < argc; extra_args++) {
+		if (!strcmp(argv[extra_args], "norc")) {
 			rc_handling_disabled = true;
 
+		} else if (!strcmp(argv[1], "hil")) {
```
Comment (bkueng) [inline src/drivers/px4io/px4io.cpp]: This should be: `strcmp(argv[extra_args], "hil"`

Comment (langrind) [reply src/drivers/px4io/px4io.cpp]: Oops, thanks, I will fix. Good eye!

**Comment by julianoes** [comment]
> @julianoes @dagar Do we want to pull this into 1.10? I'm tending towards it.

Yes, I'll backport it.

**Comment by julianoes** [comment]
> Yes, I'll backport it.

@bkueng could you please backport it. It's conflicting and I'm not aware of what has been going on here.

**Comment by langrind** [comment]
@bkueng @julianoes  - #13531 is a PR of a cherry pick from master into release/1.10 with the conflict resolved. I hope this makes your work easier. But if not, please decline it.
