### PR TITLE
Airspeed: preflight check for bad offset, fixed calls to preflight ch…

### LINKED ISSUE #5059: Airspeed circuit breaker has no effect
I found today that the only way to arm Pixhawk in fixedwing mode was with an airspeed sensor connected. The circuit breaker didn't seem to have any effect.

### LINKED ISSUE #5631: Fix preflightCheck calls and remove default value for last argument
- remove default argument here: https://github.com/PX4/Firmware/blob/master/src/modules/commander/PreflightCheck.h#L70 (this was already the reason for the last preflight check bugs)
- fix calls in commander

### PR DESCRIPTION
**Pull request by AndreasAntener**
…ecks (vtol & airspeed)

This is best used with a pitot tube cover. Without a cover and lots of wind on the ground the check will report a calibration issue. Although it's annoying to do more airspeed calibrations, this effectively got rid of all offset issues for us.

Fixes #5059 (I think)
Fixes #5631

@dagar @julianoes please have a look

### CODE REVIEW

**Comment by dagar** [comment]
I'm not sure I understand how this is different. Isn't checking the differential pressure effectively the same as the current indicated airspeed check? Except ~5 m/s instead of 6

**Comment by AndreasAntener** [comment]
Differences are:
- checks also negative offsets (and yes I made the margin smaller)
- actually fails preflight check now
- ignores check when arming (tube removed, could read airspeed at that time)
- fixes calls to check which were wrong before (for example it didn't check airspeed for VTOLs)

**Comment by dagar** [comment]
Ah right it can be negative. Thanks for the explanation, I'll do some testing.

**Comment by dagar** [comment]
Airspeed calibration fails if you blow too hard.

**Comment by AndreasAntener** [comment]
Huh, do you have an idea why? I'll give that a try too

File: src/modules/commander/PreflightCheck.cpp [hunk 1]
```diff
@@ -338,11 +338,24 @@ static bool airspeedCheck(orb_advert_t *mavlink_log_pub, bool optional, bool rep
...
+	if (time_since_boot < 1e6) {
+		// the airspeed driver filter doesn't deliver the actual value yet
+		success = false;
+		goto out;
+	}
+
+	if (fabsf(airspeed.differential_pressure_filtered_pa) > 15.0f && !prearm) {
 		if (report_fail) {
-			mavlink_log_critical(mavlink_log_pub, "AIRSPEED WARNING: WIND OR CALIBRATION ISSUE");
+			mavlink_log_critical(mavlink_log_pub, "PREFLIGHT FAIL: AIRSPEED CALIBRATION ISSUE");
```
Comment (julianoes) [inline src/modules/commander/PreflightCheck.cpp]: I would say what's wrong instead of "AIRSPEED CALIBRATION ISSUE"

File: src/modules/commander/commander_tests/state_machine_helper_test.cpp [hunk 2]
```diff
@@ -293,10 +293,10 @@ bool StateMachineHelperTest::armingStateTransitionTest(void)
 
         // Attempt transition
         transition_result_t result = arming_state_transition(&status, &battery, &safety, test->requested_state, &armed,
-        		false /* no pre-arm checks */,
-        		nullptr /* no mavlink_log_pub */,
-        		&status_flags,
-        		5.0f, check_gps);
+				false /* no pre-arm checks */,
+				nullptr /* no mavlink_log_pub */,
+				&status_flags,
```
Comment (julianoes) [inline src/modules/commander/commander_tests/state_machine_helper_test.cpp]: Indenting looks crooked, at least on github.

File: src/modules/commander/commander_tests/state_machine_helper_test.cpp [hunk 3]
```diff
@@ -293,10 +293,10 @@ bool StateMachineHelperTest::armingStateTransitionTest(void)
...
+				5.0f, check_gps, 2e6);
```
Comment (julianoes) [inline src/modules/commander/commander_tests/state_machine_helper_test.cpp]: What are these two values? Can you add a comment?

File: src/modules/commander/commander_tests/state_machine_helper_test.cpp (hunk 2 above)
Comment (AndreasAntener) [inline src/modules/commander/commander_tests/state_machine_helper_test.cpp]: It was wrong before, the git white space check complained to me :o

File: src/modules/commander/PreflightCheck.cpp (hunk 1 above)
Comment (AndreasAntener) [inline src/modules/commander/PreflightCheck.cpp]: Hm, my idea was to point to the thing that will resolve the issue. Because something like "large airspeed offset" doesn't really help I think. Other suggestions?

**Comment by AndreasAntener** [comment]
@julianoes addressed your comments
@dagar calibration succeeds for me even with max pressure (I use a tube cover that I can compress)

I fixed this up (I missed a commit for VTOL). Also @julianoes , please have a look at the last commit I added. You didn't get the failures reported via MAVLink because they got flagged as reported when they were actually not. Reproducible when telemetry or MAVLink via USB is running before the hotplug timeout is over.

**Comment by dagar** [comment]
Tried again and blowing too hard (> 5 m/s) doesn't fail calibration, but you get the critical preflight fail message which is confusing. Must be the filtered value immediately after calibration finishes?

What if the end of airspeed calibration (after the beep for successful positive pressure) we wait for the filtered pressure to drop below the preflight threshold in a reasonable time and fail calibration if it doesn't?

**Comment by AndreasAntener** [comment]
Oh I see. I would probably just delay the end of the calibration a fraction, to not duplicate the preflight check. Although you could argue that this check belongs into the calibration anyway.

**Comment by AndreasAntener** [comment]
@dagar I was able to reproduce the issue and added a commit that should prevent this in 99% of the cases. Unless the operator creates airflow for a long time it should be fine.

**Comment by dagar** [comment]
Thanks!
