### PR TITLE
Land detector cleanup fixes

### LINKED ISSUE #10593: restart land_detector problem
**Describe the bug**
restart land_detector

```
land_detector stop

land_detector start multicopter

```

will let other module such as navigator not subscribe  message vehicle_land_detected successfully

**To Reproduce**

1. land_detector stop

2. land_detector start multicopter

**Expected behavior**
position mode failed

**Log Files and Screenshots**

**Fix**
uorb message clean up in destructor

```cpp
LandDetector::~LandDetector()
{
	perf_free(_cycle_perf);
	orb_unadvertise(_landDetectedPub);
}
```

### PR DESCRIPTION
**Pull request by bkueng**
- cleanup subscriptions & publications 
- move _parameterSub to the right place

Fixes #10593

### CODE REVIEW

File: src/modules/land_detector/LandDetector.cpp [hunk 1]
```diff
@@ -60,6 +60,18 @@ LandDetector::LandDetector() :
 LandDetector::~LandDetector()
 {
 	perf_free(_cycle_perf);
+
+	if (_armingSub >= 0) {
```
Comment (dagar) [inline src/modules/land_detector/LandDetector.cpp]: Maybe we should push this check into uORB.

File: src/modules/land_detector/MulticopterLandDetector.cpp [hunk 2]
```diff
@@ -97,7 +97,6 @@ void MulticopterLandDetector::_initialize_topics()
 	_vehicleLocalPositionSetpointSub = orb_subscribe(ORB_ID(vehicle_local_position_setpoint));
 	_attitudeSub = orb_subscribe(ORB_ID(vehicle_attitude));
 	_actuatorsSub = orb_subscribe(ORB_ID(actuator_controls_0));
-	_parameterSub = orb_subscribe(ORB_ID(parameter_update));
```
Comment (dagar) [inline src/modules/land_detector/MulticopterLandDetector.cpp]: This explains some things in retrospect...
