### PR TITLE
Tools: fix ubuntu setup script

### LINKED ISSUE #14888: Ubuntu toolchain setup script fails
**Describe the bug**
When running the Ubuntu setup script (Tools/setup/ubuntu.sh) on Ubuntu 20.04, the script stops running at this line: https://github.com/PX4/Firmware/blob/0a4e7142ee7baa14cc50ea86d5a13b1933d5d5e4/Tools/setup/ubuntu.sh#L144

**To Reproduce**
Run the script on Ubuntu 20.04, after installing the NuttX dependencies it stops. When replacing the line linked above with GCC_FOUND_VER=0, the installation continues as expected.

### LINKED ISSUE #14916: ./Tools/setup/ubuntu.sh: line 149: [: missing `]'
https://github.com/PX4/Firmware/blob/master/Tools/setup/ubuntu.sh#L149

Tested on ubuntu 18.04 @ vmware and ubuntu 18.04 @ wsl.
will get this warning: ```./Tools/setup/ubuntu.sh: line 149: [: missing `]'```
This bug will cause can't detect arm-gcc already installed, will download again.

I'm not professional on this, don't know how to fix this.

### PR DESCRIPTION
**Pull request by julianoes**
This fixes the error:
`line 149: [: missing `]'`

Fixes #14916, fixes #14888.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks!!! Don't understand how it works, but it does :-)

**Comment by julianoes** [comment]
Me neither. I don't know bash. I just tried things until it worked.

**Comment by hamishwillee** [comment]
Hilarious

File: Tools/setup/ubuntu.sh [hunk 1]
```diff
@@ -146,7 +146,7 @@ if [ $(which arm-none-eabi-gcc) ]; then
 	GCC_FOUND_VER=$(echo $GCC_VER_STR | grep -c "${NUTTX_GCC_VERSION}")
 fi
 
-	if [ ! ${GCC_FOUND_VER+x} && $GCC_FOUND_VER -eq "1" ]; then
+	if [[ ! -z $GCC_FOUND_VER && $GCC_FOUND_VER -eq "1" ]]; then
```
Comment (bkueng) [inline Tools/setup/ubuntu.sh:149]: Why not just `if [ "$GCC_FOUND_VER" = "1" ]; then`?

Comment (julianoes) [reply Tools/setup/ubuntu.sh:149]: Cause I don't know bash properly. Feel free to fix :smile:

Comment (bkueng) [reply Tools/setup/ubuntu.sh:149]: https://github.com/PX4/Firmware/pull/14935
