### PR TITLE
Changed timing of actuator_controls_0 message from rover_pos_control

### LINKED ISSUE #12490: Rover SITL test failing
**Describe the bug**
Some PRs are failing the Rover SITL test, without having changed any functionality related to the rover. For example, [here](http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-12389/7/pipeline/). This is caused by an issue with the timing of the `actuator_controls_0` topic and Gazebo.

**Expected behavior**
The test should pass.

**Log Files and Screenshots**
http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-SITL_tests/detail/PR-12389/7/pipeline/

**Drone (please complete the following information):**
- SITL `gazebo_rover`

**Additional context**
This rover test was added recently, in #12117

### PR DESCRIPTION
**Pull request by ItsTimmy**
**Describe problem solved by the proposed pull request**
The `rover_pos_control` module was publishing `actuator_controls_0` messages at a constant 250Hz, independent of any polling on any other UOrb topic. This was causing issues with Gazebo where it would get slightly out of sync with sensor readings. Closes #12490 

**Test data / coverage**
Ran several missions in Gazebo.

**Describe your preferred solution**
Changed `rover_pos_control` to poll on `sensor_combined` to time the publication of `actuator_controls_0`. This sensor data is not actually used, it is only necessary for timing.

### CODE REVIEW

File: src/modules/rover_pos_control/RoverPositionControl.cpp [hunk 1]
```diff
@@ -477,7 +392,9 @@ RoverPositionControl::task_main()
 			}
 		}
 
-		if (pret == 0) {
+		if (fds[2].revents & POLLIN) {
+
+			orb_copy(ORB_ID(sensor_combined), _sensor_combined_sub, &_sensor_combined);
```
Comment (julianoes) [inline src/modules/rover_pos_control/RoverPositionControl.cpp]: It's a bit silly but it works :smile:
